import random


class Config:
    USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36"
    LANGUAHE_ID = '73efcbce-be6c-49da-a2ee-eeedf49a713d'
    CITIES = ['BNE', 'MEL', 'SYD', 'PER', 'ADL', 'ALA', 'NQZ']
    NATION_DICT = {
        "AD": "AND", "AE": "ARE", "AF": "AFG", "AG": "ATG", "AI": "AIA", "AL": "ALB", "AM": "ARM", "AO": "AGO",
        "AQ": "ATA", "AR": "ARG", "AS": "ASM", "AT": "AUT", "AU": "AUS", "AW": "ABW", "AX": "ALA", "AZ": "AZE",
        "BA": "BIH", "BB": "BRB", "BD": "BGD", "BE": "BEL", "BF": "BFA", "BG": "BGR", "BH": "BHR", "BI": "BDI",
        "BJ": "BEN", "BL": "BLM", "BM": "BMU", "BN": "BRN", "BO": "BOL", "BQ": "BES", "BR": "BRA", "BS": "BHS",
        "BT": "BTN", "BV": "BVT", "BW": "BWA", "BY": "BLR", "BZ": "BLZ", "CA": "CAN", "CC": "CCK", "CF": "CAF",
        "CH": "CHE", "CL": "DHL", "CM": "CMR", "CO": "COL", "CR": "CRI", "CU": "CUB", "CV": "CPV", "CX": "CXR",
        "CY": "CYP", "CZ": "CZE", "DE": "DEU", "DJ": "DJI", "DK": "DNK", "DM": "DMA", "DO": "DOM", "DZ": "DZA",
        "EC": "ECE", "EE": "EST", "EG": "EGY", "EH": "ESH", "ER": "ERI", "ES": "ESP", "FI": "FIN", "FJ": "FJI",
        "FK": "FLK", "FM": "FSM", "FO": "FRO", "FR": "FRA", "GA": "GAB", "GD": "GRD", "GE": "GEO", "GF": "GUF",
        "GH": "GHA", "GI": "GIB", "GL": "GRL", "GN": "GIN", "GP": "GLP", "GQ": "GNQ", "GR": "GRC", "GS": "SGS",
        "GT": "GTM", "GU": "GUM", "GW": "GNB", "GY": "GUY", "HK": "HKG", "HM": "HMD", "HN": "HND", "HR": "HRV",
        "HT": "HTI", "HU": "HUN", "ID": "IDN", "IE": "IRL", "IL": "ISR", "IM": "IMN", "IN": "IND", "IO": "IOT",
        "IQ": "IRQ", "IR": "IRN", "IS": "ISL", "IT": "ITA", "JE": "JEY", "JM": "JAM", "JO": "JOR", "JP": "JPN",
        "KH": "KHM", "KI": "KIR", "KM": "COM", "KW": "KWT", "KY": "CYM", "LB": "LBN", "LI": "LIE", "LK": "LKA",
        "LR": "LBR", "LS": "LSO", "LT": "LTU", "LU": "LUX", "LV": "LVA", "LY": "LBY", "MA": "MAR", "MC": "MCO",
        "MD": "MDA", "ME": "MNE", "MF": "MAF", "MG": "MDG", "MH": "MHL", "MK": "MKD", "ML": "MLI", "MM": "MMR",
        "MO": "MAC", "MQ": "MTQ", "MR": "MRT", "MS": "MSR", "MT": "MLT", "MV": "MDV", "MW": "MWI", "MX": "MEX",
        "MY": "MYS", "NA": "NAM", "NE": "NER", "NF": "NFK", "NG": "NGA", "NI": "NIC", "NL": "NLD", "NO": "NOR",
        "NP": "NPL", "NR": "NRU", "OM": "OMN", "PA": "PAN", "PE": "PER", "PF": "PYF", "PG": "PNG", "PH": "PHL",
        "PK": "PAK", "PL": "POL", "PN": "PCN", "PR": "PRI", "PS": "PSE", "PW": "PLW", "PY": "PRY", "QA": "QAT",
        "RE": "REU", "RO": "ROU", "RS": "SRB", "RU": "RUS", "RW": "RWA", "SB": "SLB", "SC": "SYC", "SD": "SDN",
        "SE": "SWE", "SG": "SGP", "SI": "SVN", "SJ": "SJM", "SK": "SVK", "SL": "SLE", "SM": "SMR", "SN": "SEN",
        "SO": "SOM", "SR": "SUR", "SS": "SSD", "ST": "STP", "SV": "SLV", "SY": "SYR", "SZ": "SWZ", "TC": "TCA",
        "TD": "TCD", "TG": "TGO", "TH": "THA", "TK": "TKL", "TL": "TLS", "TN": "TUN", "TO": "TON", "TR": "TUR",
        "TV": "TUV", "TZ": "TZA", "UA": "UKR", "UG": "UGA", "US": "USA", "UY": "URY", "VA": "VAT", "VE": "VEN",
        "VG": "VGB", "VI": "VIR", "VN": "VNM", "WF": "WLF", "WS": "WSM", "YE": "YEM", "YT": "MYT", "ZA": "ZAF",
        "ZM": "ZMB", "ZW": "ZWE", "CN": "CHN", "CG": "COG", "CD": "COD", "MZ": "MOZ", "GG": "GGY", "GM": "GMB",
        "MP": "MNP", "ET": "ETH", "NC": "NCL", "VU": "VUT", "TF": "ATF", "NU": "NIU", "UM": "UMI", "CK": "COK",
        "GB": "GBR", "TT": "TTO", "VC": "VCT", "TW": "TWN", "NZ": "NZL", "SA": "SAU", "LA": "LAO", "KP": "PRK",
        "KR": "KOR", "PT": "PRT", "KG": "KGZ", "KZ": "KAZ", "TJ": "TJK", "TM": "TKM", "UZ": "UZB", "KN": "KNA",
        "PM": "SPM", "SH": "SHN", "LC": "LCA", "MU": "MUS", "CI": "CIV", "KE": "KEN", "MN": "MNG"}
    Country_Code_Dict = {'93': {'country': 'Afghanistan', 'isoCode': 'AF', 'isoCode1': 'AFG'},
                         '355': {'country': 'Albania', 'isoCode': 'AL', 'isoCode1': 'ALB'},
                         '213': {'country': 'Algeria', 'isoCode': 'DZ', 'isoCode1': 'DZA'},
                         '1684': {'country': 'American Samoa', 'isoCode': 'AS', 'isoCode1': 'ASM'},
                         '376': {'country': 'Andorra', 'isoCode': 'AD', 'isoCode1': 'AND'},
                         '244': {'country': 'Angola', 'isoCode': 'AO', 'isoCode1': 'AGO'},
                         '1264': {'country': 'Anguilla', 'isoCode': 'AI', 'isoCode1': 'AIA'},
                         '672': {'country': 'Antarctica', 'isoCode': 'AQ', 'isoCode1': 'ATA'},
                         '1268': {'country': 'Antigua and Barbuda', 'isoCode': 'AG', 'isoCode1': 'ATG'},
                         '54': {'country': 'Argentina', 'isoCode': 'AR', 'isoCode1': 'ARG'},
                         '374': {'country': 'Armenia', 'isoCode': 'AM', 'isoCode1': 'ARM'},
                         '297': {'country': 'Aruba', 'isoCode': 'AW', 'isoCode1': 'ABW'},
                         '61': {'country': 'Cocos Islands', 'isoCode': 'CC', 'isoCode1': 'CCK'},
                         '43': {'country': 'Austria', 'isoCode': 'AT', 'isoCode1': 'AUT'},
                         '994': {'country': 'Azerbaijan', 'isoCode': 'AZ', 'isoCode1': 'AZE'},
                         '1242': {'country': 'Bahamas', 'isoCode': 'BS', 'isoCode1': 'BHS'},
                         '973': {'country': 'Bahrain', 'isoCode': 'BH', 'isoCode1': 'BHR'},
                         '880': {'country': 'Bangladesh', 'isoCode': 'BD', 'isoCode1': 'BGD'},
                         '1246': {'country': 'Barbados', 'isoCode': 'BB', 'isoCode1': 'BRB'},
                         '375': {'country': 'Belarus', 'isoCode': 'BY', 'isoCode1': 'BLR'},
                         '32': {'country': 'Belgium', 'isoCode': 'BE', 'isoCode1': 'BEL'},
                         '501': {'country': 'Belize', 'isoCode': 'BZ', 'isoCode1': 'BLZ'},
                         '229': {'country': 'Benin', 'isoCode': 'BJ', 'isoCode1': 'BEN'},
                         '1441': {'country': 'Bermuda', 'isoCode': 'BM', 'isoCode1': 'BMU'},
                         '975': {'country': 'Bhutan', 'isoCode': 'BT', 'isoCode1': 'BTN'},
                         '591': {'country': 'Bolivia', 'isoCode': 'BO', 'isoCode1': 'BOL'},
                         '387': {'country': 'Bosnia and Herzegovina', 'isoCode': 'BA', 'isoCode1': 'BIH'},
                         '267': {'country': 'Botswana', 'isoCode': 'BW', 'isoCode1': 'BWA'},
                         '55': {'country': 'Brazil', 'isoCode': 'BR', 'isoCode1': 'BRA'},
                         '246': {'country': 'British Indian Ocean Territory', 'isoCode': 'IO', 'isoCode1': 'IOT'},
                         '1284': {'country': 'British Virgin Islands', 'isoCode': 'VG', 'isoCode1': 'VGB'},
                         '673': {'country': 'Brunei', 'isoCode': 'BN', 'isoCode1': 'BRN'},
                         '359': {'country': 'Bulgaria', 'isoCode': 'BG', 'isoCode1': 'BGR'},
                         '226': {'country': 'Burkina Faso', 'isoCode': 'BF', 'isoCode1': 'BFA'},
                         '95': {'country': 'Myanmar', 'isoCode': 'MM', 'isoCode1': 'MMR'},
                         '257': {'country': 'Burundi', 'isoCode': 'BI', 'isoCode1': 'BDI'},
                         '855': {'country': 'Cambodia', 'isoCode': 'KH', 'isoCode1': 'KHM'},
                         '237': {'country': 'Cameroon', 'isoCode': 'CM', 'isoCode1': 'CMR'},
                         '1': {'country': 'United States', 'isoCode': 'US', 'isoCode1': 'USA'},
                         '238': {'country': 'Cape Verde', 'isoCode': 'CV', 'isoCode1': 'CPV'},
                         '1345': {'country': 'Cayman Islands', 'isoCode': 'KY', 'isoCode1': 'CYM'},
                         '236': {'country': 'Central African Republic', 'isoCode': 'CF', 'isoCode1': 'CAF'},
                         '235': {'country': 'Chad', 'isoCode': 'TD', 'isoCode1': 'TCD'},
                         '56': {'country': 'Chile', 'isoCode': 'CL', 'isoCode1': 'CHL'},
                         '86': {'country': 'China', 'isoCode': 'CN', 'isoCode1': 'CHN'},
                         '57': {'country': 'Colombia', 'isoCode': 'CO', 'isoCode1': 'COL'},
                         '269': {'country': 'Comoros', 'isoCode': 'KM', 'isoCode1': 'COM'},
                         '242': {'country': 'Republic of the Congo', 'isoCode': 'CG', 'isoCode1': 'COG'},
                         '243': {'country': 'Democratic Republic of the Congo', 'isoCode': 'CD', 'isoCode1': 'COD'},
                         '682': {'country': 'Cook Islands', 'isoCode': 'CK', 'isoCode1': 'COK'},
                         '506': {'country': 'Costa Rica', 'isoCode': 'CR', 'isoCode1': 'CRI'},
                         '385': {'country': 'Croatia', 'isoCode': 'HR', 'isoCode1': 'HRV'},
                         '53': {'country': 'Cuba', 'isoCode': 'CU', 'isoCode1': 'CUB'},
                         '599': {'country': 'Netherlands Antilles', 'isoCode': 'AN', 'isoCode1': 'ANT'},
                         '357': {'country': 'Cyprus', 'isoCode': 'CY', 'isoCode1': 'CYP'},
                         '420': {'country': 'Czech Republic', 'isoCode': 'CZ', 'isoCode1': 'CZE'},
                         '45': {'country': 'Denmark', 'isoCode': 'DK', 'isoCode1': 'DNK'},
                         '253': {'country': 'Djibouti', 'isoCode': 'DJ', 'isoCode1': 'DJI'},
                         '1767': {'country': 'Dominica', 'isoCode': 'DM', 'isoCode1': 'DMA'},
                         '670': {'country': 'East Timor', 'isoCode': 'TL', 'isoCode1': 'TLS'},
                         '593': {'country': 'Ecuador', 'isoCode': 'EC', 'isoCode1': 'ECU'},
                         '20': {'country': 'Egypt', 'isoCode': 'EG', 'isoCode1': 'EGY'},
                         '503': {'country': 'El Salvador', 'isoCode': 'SV', 'isoCode1': 'SLV'},
                         '240': {'country': 'Equatorial Guinea', 'isoCode': 'GQ', 'isoCode1': 'GNQ'},
                         '291': {'country': 'Eritrea', 'isoCode': 'ER', 'isoCode1': 'ERI'},
                         '372': {'country': 'Estonia', 'isoCode': 'EE', 'isoCode1': 'EST'},
                         '251': {'country': 'Ethiopia', 'isoCode': 'ET', 'isoCode1': 'ETH'},
                         '500': {'country': 'Falkland Islands', 'isoCode': 'FK', 'isoCode1': 'FLK'},
                         '298': {'country': 'Faroe Islands', 'isoCode': 'FO', 'isoCode1': 'FRO'},
                         '679': {'country': 'Fiji', 'isoCode': 'FJ', 'isoCode1': 'FJI'},
                         '358': {'country': 'Finland', 'isoCode': 'FI', 'isoCode1': 'FIN'},
                         '33': {'country': 'France', 'isoCode': 'FR', 'isoCode1': 'FRA'},
                         '689': {'country': 'French Polynesia', 'isoCode': 'PF', 'isoCode1': 'PYF'},
                         '241': {'country': 'Gabon', 'isoCode': 'GA', 'isoCode1': 'GAB'},
                         '220': {'country': 'Gambia', 'isoCode': 'GM', 'isoCode1': 'GMB'},
                         '995': {'country': 'Georgia', 'isoCode': 'GE', 'isoCode1': 'GEO'},
                         '49': {'country': 'Germany', 'isoCode': 'DE', 'isoCode1': 'DEU'},
                         '233': {'country': 'Ghana', 'isoCode': 'GH', 'isoCode1': 'GHA'},
                         '350': {'country': 'Gibraltar', 'isoCode': 'GI', 'isoCode1': 'GIB'},
                         '30': {'country': 'Greece', 'isoCode': 'GR', 'isoCode1': 'GRC'},
                         '299': {'country': 'Greenland', 'isoCode': 'GL', 'isoCode1': 'GRL'},
                         '1473': {'country': 'Grenada', 'isoCode': 'GD', 'isoCode1': 'GRD'},
                         '1671': {'country': 'Guam', 'isoCode': 'GU', 'isoCode1': 'GUM'},
                         '502': {'country': 'Guatemala', 'isoCode': 'GT', 'isoCode1': 'GTM'},
                         '44-1481': {'country': 'Guernsey', 'isoCode': 'GG', 'isoCode1': 'GGY'},
                         '224': {'country': 'Guinea', 'isoCode': 'GN', 'isoCode1': 'GIN'},
                         '245': {'country': 'Guinea-Bissau', 'isoCode': 'GW', 'isoCode1': 'GNB'},
                         '592': {'country': 'Guyana', 'isoCode': 'GY', 'isoCode1': 'GUY'},
                         '509': {'country': 'Haiti', 'isoCode': 'HT', 'isoCode1': 'HTI'},
                         '504': {'country': 'Honduras', 'isoCode': 'HN', 'isoCode1': 'HND'},
                         '852': {'country': 'Hong Kong', 'isoCode': 'HK', 'isoCode1': 'HKG'},
                         '36': {'country': 'Hungary', 'isoCode': 'HU', 'isoCode1': 'HUN'},
                         '354': {'country': 'Iceland', 'isoCode': 'IS', 'isoCode1': 'ISL'},
                         '91': {'country': 'India', 'isoCode': 'IN', 'isoCode1': 'IND'},
                         '62': {'country': 'Indonesia', 'isoCode': 'ID', 'isoCode1': 'IDN'},
                         '98': {'country': 'Iran', 'isoCode': 'IR', 'isoCode1': 'IRN'},
                         '964': {'country': 'Iraq', 'isoCode': 'IQ', 'isoCode1': 'IRQ'},
                         '353': {'country': 'Ireland', 'isoCode': 'IE', 'isoCode1': 'IRL'},
                         '44-1624': {'country': 'Isle of Man', 'isoCode': 'IM', 'isoCode1': 'IMN'},
                         '972': {'country': 'Israel', 'isoCode': 'IL', 'isoCode1': 'ISR'},
                         '39': {'country': 'Italy', 'isoCode': 'IT', 'isoCode1': 'ITA'},
                         '225': {'country': 'Ivory Coast', 'isoCode': 'CI', 'isoCode1': 'CIV'},
                         '1-876': {'country': 'Jamaica', 'isoCode': 'JM', 'isoCode1': 'JAM'},
                         '81': {'country': 'Japan', 'isoCode': 'JP', 'isoCode1': 'JPN'},
                         '44-1534': {'country': 'Jersey', 'isoCode': 'JE', 'isoCode1': 'JEY'},
                         '962': {'country': 'Jordan', 'isoCode': 'JO', 'isoCode1': 'JOR'},
                         '7': {'country': 'Russia', 'isoCode': 'RU', 'isoCode1': 'RUS'},
                         '254': {'country': 'Kenya', 'isoCode': 'KE', 'isoCode1': 'KEN'},
                         '686': {'country': 'Kiribati', 'isoCode': 'KI', 'isoCode1': 'KIR'},
                         '383': {'country': 'Kosovo', 'isoCode': 'XK', 'isoCode1': 'XKX'},
                         '965': {'country': 'Kuwait', 'isoCode': 'KW', 'isoCode1': 'KWT'},
                         '996': {'country': 'Kyrgyzstan', 'isoCode': 'KG', 'isoCode1': 'KGZ'},
                         '856': {'country': 'Laos', 'isoCode': 'LA', 'isoCode1': 'LAO'},
                         '371': {'country': 'Latvia', 'isoCode': 'LV', 'isoCode1': 'LVA'},
                         '961': {'country': 'Lebanon', 'isoCode': 'LB', 'isoCode1': 'LBN'},
                         '266': {'country': 'Lesotho', 'isoCode': 'LS', 'isoCode1': 'LSO'},
                         '231': {'country': 'Liberia', 'isoCode': 'LR', 'isoCode1': 'LBR'},
                         '218': {'country': 'Libya', 'isoCode': 'LY', 'isoCode1': 'LBY'},
                         '423': {'country': 'Liechtenstein', 'isoCode': 'LI', 'isoCode1': 'LIE'},
                         '370': {'country': 'Lithuania', 'isoCode': 'LT', 'isoCode1': 'LTU'},
                         '352': {'country': 'Luxembourg', 'isoCode': 'LU', 'isoCode1': 'LUX'},
                         '853': {'country': 'Macau', 'isoCode': 'MO', 'isoCode1': 'MAC'},
                         '389': {'country': 'Macedonia', 'isoCode': 'MK', 'isoCode1': 'MKD'},
                         '261': {'country': 'Madagascar', 'isoCode': 'MG', 'isoCode1': 'MDG'},
                         '265': {'country': 'Malawi', 'isoCode': 'MW', 'isoCode1': 'MWI'},
                         '60': {'country': 'Malaysia', 'isoCode': 'MY', 'isoCode1': 'MYS'},
                         '960': {'country': 'Maldives', 'isoCode': 'MV', 'isoCode1': 'MDV'},
                         '223': {'country': 'Mali', 'isoCode': 'ML', 'isoCode1': 'MLI'},
                         '356': {'country': 'Malta', 'isoCode': 'MT', 'isoCode1': 'MLT'},
                         '692': {'country': 'Marshall Islands', 'isoCode': 'MH', 'isoCode1': 'MHL'},
                         '222': {'country': 'Mauritania', 'isoCode': 'MR', 'isoCode1': 'MRT'},
                         '230': {'country': 'Mauritius', 'isoCode': 'MU', 'isoCode1': 'MUS'},
                         '262': {'country': 'Reunion', 'isoCode': 'RE', 'isoCode1': 'REU'},
                         '52': {'country': 'Mexico', 'isoCode': 'MX', 'isoCode1': 'MEX'},
                         '691': {'country': 'Micronesia', 'isoCode': 'FM', 'isoCode1': 'FSM'},
                         '373': {'country': 'Moldova', 'isoCode': 'MD', 'isoCode1': 'MDA'},
                         '377': {'country': 'Monaco', 'isoCode': 'MC', 'isoCode1': 'MCO'},
                         '976': {'country': 'Mongolia', 'isoCode': 'MN', 'isoCode1': 'MNG'},
                         '382': {'country': 'Montenegro', 'isoCode': 'ME', 'isoCode1': 'MNE'},
                         '1-664': {'country': 'Montserrat', 'isoCode': 'MS', 'isoCode1': 'MSR'},
                         '212': {'country': 'Western Sahara', 'isoCode': 'EH', 'isoCode1': 'ESH'},
                         '258': {'country': 'Mozambique', 'isoCode': 'MZ', 'isoCode1': 'MOZ'},
                         '264': {'country': 'Namibia', 'isoCode': 'NA', 'isoCode1': 'NAM'},
                         '674': {'country': 'Nauru', 'isoCode': 'NR', 'isoCode1': 'NRU'},
                         '977': {'country': 'Nepal', 'isoCode': 'NP', 'isoCode1': 'NPL'},
                         '31': {'country': 'Netherlands', 'isoCode': 'NL', 'isoCode1': 'NLD'},
                         '687': {'country': 'New Caledonia', 'isoCode': 'NC', 'isoCode1': 'NCL'},
                         '64': {'country': 'Pitcairn', 'isoCode': 'PN', 'isoCode1': 'PCN'},
                         '505': {'country': 'Nicaragua', 'isoCode': 'NI', 'isoCode1': 'NIC'},
                         '227': {'country': 'Niger', 'isoCode': 'NE', 'isoCode1': 'NER'},
                         '234': {'country': 'Nigeria', 'isoCode': 'NG', 'isoCode1': 'NGA'},
                         '683': {'country': 'Niue', 'isoCode': 'NU', 'isoCode1': 'NIU'},
                         '1-670': {'country': 'Northern Mariana Islands', 'isoCode': 'MP', 'isoCode1': 'MNP'},
                         '850': {'country': 'North Korea', 'isoCode': 'KP', 'isoCode1': 'PRK'},
                         '47': {'country': 'Svalbard and Jan Mayen', 'isoCode': 'SJ', 'isoCode1': 'SJM'},
                         '968': {'country': 'Oman', 'isoCode': 'OM', 'isoCode1': 'OMN'},
                         '92': {'country': 'Pakistan', 'isoCode': 'PK', 'isoCode1': 'PAK'},
                         '680': {'country': 'Palau', 'isoCode': 'PW', 'isoCode1': 'PLW'},
                         '970': {'country': 'Palestine', 'isoCode': 'PS', 'isoCode1': 'PSE'},
                         '507': {'country': 'Panama', 'isoCode': 'PA', 'isoCode1': 'PAN'},
                         '675': {'country': 'Papua New Guinea', 'isoCode': 'PG', 'isoCode1': 'PNG'},
                         '595': {'country': 'Paraguay', 'isoCode': 'PY', 'isoCode1': 'PRY'},
                         '51': {'country': 'Peru', 'isoCode': 'PE', 'isoCode1': 'PER'},
                         '63': {'country': 'Philippines', 'isoCode': 'PH', 'isoCode1': 'PHL'},
                         '48': {'country': 'Poland', 'isoCode': 'PL', 'isoCode1': 'POL'},
                         '351': {'country': 'Portugal', 'isoCode': 'PT', 'isoCode1': 'PRT'},
                         '1-787, 1-939': {'country': 'Puerto Rico', 'isoCode': 'PR', 'isoCode1': 'PRI'},
                         '974': {'country': 'Qatar', 'isoCode': 'QA', 'isoCode1': 'QAT'},
                         '40': {'country': 'Romania', 'isoCode': 'RO', 'isoCode1': 'ROU'},
                         '250': {'country': 'Rwanda', 'isoCode': 'RW', 'isoCode1': 'RWA'},
                         '590': {'country': 'Saint Martin', 'isoCode': 'MF', 'isoCode1': 'MAF'},
                         '685': {'country': 'Samoa', 'isoCode': 'WS', 'isoCode1': 'WSM'},
                         '378': {'country': 'San Marino', 'isoCode': 'SM', 'isoCode1': 'SMR'},
                         '239': {'country': 'Sao Tome and Principe', 'isoCode': 'ST', 'isoCode1': 'STP'},
                         '966': {'country': 'Saudi Arabia', 'isoCode': 'SA', 'isoCode1': 'SAU'},
                         '221': {'country': 'Senegal', 'isoCode': 'SN', 'isoCode1': 'SEN'},
                         '381': {'country': 'Serbia', 'isoCode': 'RS', 'isoCode1': 'SRB'},
                         '248': {'country': 'Seychelles', 'isoCode': 'SC', 'isoCode1': 'SYC'},
                         '232': {'country': 'Sierra Leone', 'isoCode': 'SL', 'isoCode1': 'SLE'},
                         '65': {'country': 'Singapore', 'isoCode': 'SG', 'isoCode1': 'SGP'},
                         '1-721': {'country': 'Sint Maarten', 'isoCode': 'SX', 'isoCode1': 'SXM'},
                         '421': {'country': 'Slovakia', 'isoCode': 'SK', 'isoCode1': 'SVK'},
                         '386': {'country': 'Slovenia', 'isoCode': 'SI', 'isoCode1': 'SVN'},
                         '677': {'country': 'Solomon Islands', 'isoCode': 'SB', 'isoCode1': 'SLB'},
                         '252': {'country': 'Somalia', 'isoCode': 'SO', 'isoCode1': 'SOM'},
                         '27': {'country': 'South Africa', 'isoCode': 'ZA', 'isoCode1': 'ZAF'},
                         '82': {'country': 'South Korea', 'isoCode': 'KR', 'isoCode1': 'KOR'},
                         '211': {'country': 'South Sudan', 'isoCode': 'SS', 'isoCode1': 'SSD'},
                         '34': {'country': 'Spain', 'isoCode': 'ES', 'isoCode1': 'ESP'},
                         '94': {'country': 'Sri Lanka', 'isoCode': 'LK', 'isoCode1': 'LKA'},
                         '290': {'country': 'Saint Helena', 'isoCode': 'SH', 'isoCode1': 'SHN'},
                         '1-869': {'country': 'Saint Kitts and Nevis', 'isoCode': 'KN', 'isoCode1': 'KNA'},
                         '1-758': {'country': 'Saint Lucia', 'isoCode': 'LC', 'isoCode1': 'LCA'},
                         '508': {'country': 'Saint Pierre and Miquelon', 'isoCode': 'PM', 'isoCode1': 'SPM'},
                         '1-784': {'country': 'Saint Vincent and the Grenadines', 'isoCode': 'VC', 'isoCode1': 'VCT'},
                         '249': {'country': 'Sudan', 'isoCode': 'SD', 'isoCode1': 'SDN'},
                         '597': {'country': 'Suriname', 'isoCode': 'SR', 'isoCode1': 'SUR'},
                         '268': {'country': 'Swaziland', 'isoCode': 'SZ', 'isoCode1': 'SWZ'},
                         '46': {'country': 'Sweden', 'isoCode': 'SE', 'isoCode1': 'SWE'},
                         '41': {'country': 'Switzerland', 'isoCode': 'CH', 'isoCode1': 'CHE'},
                         '963': {'country': 'Syria', 'isoCode': 'SY', 'isoCode1': 'SYR'},
                         '886': {'country': 'Taiwan', 'isoCode': 'TW', 'isoCode1': 'TWN'},
                         '992': {'country': 'Tajikistan', 'isoCode': 'TJ', 'isoCode1': 'TJK'},
                         '255': {'country': 'Tanzania', 'isoCode': 'TZ', 'isoCode1': 'TZA'},
                         '66': {'country': 'Thailand', 'isoCode': 'TH', 'isoCode1': 'THA'},
                         '228': {'country': 'Togo', 'isoCode': 'TG', 'isoCode1': 'TGO'},
                         '690': {'country': 'Tokelau', 'isoCode': 'TK', 'isoCode1': 'TKL'},
                         '676': {'country': 'Tonga', 'isoCode': 'TO', 'isoCode1': 'TON'},
                         '1-868': {'country': 'Trinidad and Tobago', 'isoCode': 'TT', 'isoCode1': 'TTO'},
                         '216': {'country': 'Tunisia', 'isoCode': 'TN', 'isoCode1': 'TUN'},
                         '90': {'country': 'Turkey', 'isoCode': 'TR', 'isoCode1': 'TUR'},
                         '993': {'country': 'Turkmenistan', 'isoCode': 'TM', 'isoCode1': 'TKM'},
                         '1-649': {'country': 'Turks and Caicos Islands', 'isoCode': 'TC', 'isoCode1': 'TCA'},
                         '688': {'country': 'Tuvalu', 'isoCode': 'TV', 'isoCode1': 'TUV'},
                         '971': {'country': 'United Arab Emirates', 'isoCode': 'AE', 'isoCode1': 'ARE'},
                         '256': {'country': 'Uganda', 'isoCode': 'UG', 'isoCode1': 'UGA'},
                         '44': {'country': 'United Kingdom', 'isoCode': 'GB', 'isoCode1': 'GBR'},
                         '380': {'country': 'Ukraine', 'isoCode': 'UA', 'isoCode1': 'UKR'},
                         '598': {'country': 'Uruguay', 'isoCode': 'UY', 'isoCode1': 'URY'},
                         '998': {'country': 'Uzbekistan', 'isoCode': 'UZ', 'isoCode1': 'UZB'},
                         '678': {'country': 'Vanuatu', 'isoCode': 'VU', 'isoCode1': 'VUT'},
                         '379': {'country': 'Vatican', 'isoCode': 'VA', 'isoCode1': 'VAT'},
                         '58': {'country': 'Venezuela', 'isoCode': 'VE', 'isoCode1': 'VEN'},
                         '84': {'country': 'Vietnam', 'isoCode': 'VN', 'isoCode1': 'VNM'},
                         '1-340': {'country': 'U.S. Virgin Islands', 'isoCode': 'VI', 'isoCode1': 'VIR'},
                         '681': {'country': 'Wallis and Futuna', 'isoCode': 'WF', 'isoCode1': 'WLF'},
                         '967': {'country': 'Yemen', 'isoCode': 'YE', 'isoCode1': 'YEM'},
                         '260': {'country': 'Zambia', 'isoCode': 'ZM', 'isoCode1': 'ZMB'},
                         '263': {'country': 'Zimbabwe', 'isoCode': 'ZW', 'isoCode1': 'ZWE'}}
    ISO2_MAP = {'AF': {'country': 'Afghanistan', 'code': '93', 'isoCode1': 'AFG'}, 'AL': {'country': 'Albania', 'code': '355', 'isoCode1': 'ALB'}, 'DZ': {'country': 'Algeria', 'code': '213', 'isoCode1': 'DZA'}, 'AS': {'country': 'American Samoa', 'code': '1684', 'isoCode1': 'ASM'}, 'AD': {'country': 'Andorra', 'code': '376', 'isoCode1': 'AND'}, 'AO': {'country': 'Angola', 'code': '244', 'isoCode1': 'AGO'}, 'AI': {'country': 'Anguilla', 'code': '1264', 'isoCode1': 'AIA'}, 'AQ': {'country': 'Antarctica', 'code': '672', 'isoCode1': 'ATA'}, 'AG': {'country': 'Antigua and Barbuda', 'code': '1268', 'isoCode1': 'ATG'}, 'AR': {'country': 'Argentina', 'code': '54', 'isoCode1': 'ARG'}, 'AM': {'country': 'Armenia', 'code': '374', 'isoCode1': 'ARM'}, 'AW': {'country': 'Aruba', 'code': '297', 'isoCode1': 'ABW'}, 'AU': {'country': 'Australia', 'code': '61', 'isoCode1': 'AUS'}, 'AT': {'country': 'Austria', 'code': '43', 'isoCode1': 'AUT'}, 'AZ': {'country': 'Azerbaijan', 'code': '994', 'isoCode1': 'AZE'}, 'BS': {'country': 'Bahamas', 'code': '1242', 'isoCode1': 'BHS'}, 'BH': {'country': 'Bahrain', 'code': '973', 'isoCode1': 'BHR'}, 'BD': {'country': 'Bangladesh', 'code': '880', 'isoCode1': 'BGD'}, 'BB': {'country': 'Barbados', 'code': '1246', 'isoCode1': 'BRB'}, 'BY': {'country': 'Belarus', 'code': '375', 'isoCode1': 'BLR'}, 'BE': {'country': 'Belgium', 'code': '32', 'isoCode1': 'BEL'}, 'BZ': {'country': 'Belize', 'code': '501', 'isoCode1': 'BLZ'}, 'BJ': {'country': 'Benin', 'code': '229', 'isoCode1': 'BEN'}, 'BM': {'country': 'Bermuda', 'code': '1441', 'isoCode1': 'BMU'}, 'BT': {'country': 'Bhutan', 'code': '975', 'isoCode1': 'BTN'}, 'BO': {'country': 'Bolivia', 'code': '591', 'isoCode1': 'BOL'}, 'BA': {'country': 'Bosnia and Herzegovina', 'code': '387', 'isoCode1': 'BIH'}, 'BW': {'country': 'Botswana', 'code': '267', 'isoCode1': 'BWA'}, 'BR': {'country': 'Brazil', 'code': '55', 'isoCode1': 'BRA'}, 'IO': {'country': 'British Indian Ocean Territory', 'code': '246', 'isoCode1': 'IOT'}, 'VG': {'country': 'British Virgin Islands', 'code': '1284', 'isoCode1': 'VGB'}, 'BN': {'country': 'Brunei', 'code': '673', 'isoCode1': 'BRN'}, 'BG': {'country': 'Bulgaria', 'code': '359', 'isoCode1': 'BGR'}, 'BF': {'country': 'Burkina Faso', 'code': '226', 'isoCode1': 'BFA'}, 'MM': {'country': 'Myanmar', 'code': '95', 'isoCode1': 'MMR'}, 'BI': {'country': 'Burundi', 'code': '257', 'isoCode1': 'BDI'}, 'KH': {'country': 'Cambodia', 'code': '855', 'isoCode1': 'KHM'}, 'CM': {'country': 'Cameroon', 'code': '237', 'isoCode1': 'CMR'}, 'CA': {'country': 'Canada', 'code': '1', 'isoCode1': 'CAN'}, 'CV': {'country': 'Cape Verde', 'code': '238', 'isoCode1': 'CPV'}, 'KY': {'country': 'Cayman Islands', 'code': '1345', 'isoCode1': 'CYM'}, 'CF': {'country': 'Central African Republic', 'code': '236', 'isoCode1': 'CAF'}, 'TD': {'country': 'Chad', 'code': '235', 'isoCode1': 'TCD'}, 'CL': {'country': 'Chile', 'code': '56', 'isoCode1': 'CHL'}, 'CN': {'country': 'China', 'code': '86', 'isoCode1': 'CHN'}, 'CX': {'country': 'Christmas Island', 'code': '61', 'isoCode1': 'CXR'}, 'CC': {'country': 'Cocos Islands', 'code': '61', 'isoCode1': 'CCK'}, 'CO': {'country': 'Colombia', 'code': '57', 'isoCode1': 'COL'}, 'KM': {'country': 'Comoros', 'code': '269', 'isoCode1': 'COM'}, 'CG': {'country': 'Republic of the Congo', 'code': '242', 'isoCode1': 'COG'}, 'CD': {'country': 'Democratic Republic of the Congo', 'code': '243', 'isoCode1': 'COD'}, 'CK': {'country': 'Cook Islands', 'code': '682', 'isoCode1': 'COK'}, 'CR': {'country': 'Costa Rica', 'code': '506', 'isoCode1': 'CRI'}, 'HR': {'country': 'Croatia', 'code': '385', 'isoCode1': 'HRV'}, 'CU': {'country': 'Cuba', 'code': '53', 'isoCode1': 'CUB'}, 'CW': {'country': 'Curacao', 'code': '599', 'isoCode1': 'CUW'}, 'CY': {'country': 'Cyprus', 'code': '357', 'isoCode1': 'CYP'}, 'CZ': {'country': 'Czech Republic', 'code': '420', 'isoCode1': 'CZE'}, 'DK': {'country': 'Denmark', 'code': '45', 'isoCode1': 'DNK'}, 'DJ': {'country': 'Djibouti', 'code': '253', 'isoCode1': 'DJI'}, 'DM': {'country': 'Dominica', 'code': '1767', 'isoCode1': 'DMA'}, 'DO': {'country': 'Dominican Republic', 'code': '1', 'isoCode1': 'DOM'}, 'TL': {'country': 'East Timor', 'code': '670', 'isoCode1': 'TLS'}, 'EC': {'country': 'Ecuador', 'code': '593', 'isoCode1': 'ECU'}, 'EG': {'country': 'Egypt', 'code': '20', 'isoCode1': 'EGY'}, 'SV': {'country': 'El Salvador', 'code': '503', 'isoCode1': 'SLV'}, 'GQ': {'country': 'Equatorial Guinea', 'code': '240', 'isoCode1': 'GNQ'}, 'ER': {'country': 'Eritrea', 'code': '291', 'isoCode1': 'ERI'}, 'EE': {'country': 'Estonia', 'code': '372', 'isoCode1': 'EST'}, 'ET': {'country': 'Ethiopia', 'code': '251', 'isoCode1': 'ETH'}, 'FK': {'country': 'Falkland Islands', 'code': '500', 'isoCode1': 'FLK'}, 'FO': {'country': 'Faroe Islands', 'code': '298', 'isoCode1': 'FRO'}, 'FJ': {'country': 'Fiji', 'code': '679', 'isoCode1': 'FJI'}, 'FI': {'country': 'Finland', 'code': '358', 'isoCode1': 'FIN'}, 'FR': {'country': 'France', 'code': '33', 'isoCode1': 'FRA'}, 'PF': {'country': 'French Polynesia', 'code': '689', 'isoCode1': 'PYF'}, 'GA': {'country': 'Gabon', 'code': '241', 'isoCode1': 'GAB'}, 'GM': {'country': 'Gambia', 'code': '220', 'isoCode1': 'GMB'}, 'GE': {'country': 'Georgia', 'code': '995', 'isoCode1': 'GEO'}, 'DE': {'country': 'Germany', 'code': '49', 'isoCode1': 'DEU'}, 'GH': {'country': 'Ghana', 'code': '233', 'isoCode1': 'GHA'}, 'GI': {'country': 'Gibraltar', 'code': '350', 'isoCode1': 'GIB'}, 'GR': {'country': 'Greece', 'code': '30', 'isoCode1': 'GRC'}, 'GL': {'country': 'Greenland', 'code': '299', 'isoCode1': 'GRL'}, 'GD': {'country': 'Grenada', 'code': '1473', 'isoCode1': 'GRD'}, 'GU': {'country': 'Guam', 'code': '1671', 'isoCode1': 'GUM'}, 'GT': {'country': 'Guatemala', 'code': '502', 'isoCode1': 'GTM'}, 'GG': {'country': 'Guernsey', 'code': '44-1481', 'isoCode1': 'GGY'}, 'GN': {'country': 'Guinea', 'code': '224', 'isoCode1': 'GIN'}, 'GW': {'country': 'Guinea-Bissau', 'code': '245', 'isoCode1': 'GNB'}, 'GY': {'country': 'Guyana', 'code': '592', 'isoCode1': 'GUY'}, 'HT': {'country': 'Haiti', 'code': '509', 'isoCode1': 'HTI'}, 'HN': {'country': 'Honduras', 'code': '504', 'isoCode1': 'HND'}, 'HK': {'country': 'Hong Kong', 'code': '852', 'isoCode1': 'HKG'}, 'HU': {'country': 'Hungary', 'code': '36', 'isoCode1': 'HUN'}, 'IS': {'country': 'Iceland', 'code': '354', 'isoCode1': 'ISL'}, 'IN': {'country': 'India', 'code': '91', 'isoCode1': 'IND'}, 'ID': {'country': 'Indonesia', 'code': '62', 'isoCode1': 'IDN'}, 'IR': {'country': 'Iran', 'code': '98', 'isoCode1': 'IRN'}, 'IQ': {'country': 'Iraq', 'code': '964', 'isoCode1': 'IRQ'}, 'IE': {'country': 'Ireland', 'code': '353', 'isoCode1': 'IRL'}, 'IM': {'country': 'Isle of Man', 'code': '44-1624', 'isoCode1': 'IMN'}, 'IL': {'country': 'Israel', 'code': '972', 'isoCode1': 'ISR'}, 'IT': {'country': 'Italy', 'code': '39', 'isoCode1': 'ITA'}, 'CI': {'country': 'Ivory Coast', 'code': '225', 'isoCode1': 'CIV'}, 'JM': {'country': 'Jamaica', 'code': '1-876', 'isoCode1': 'JAM'}, 'JP': {'country': 'Japan', 'code': '81', 'isoCode1': 'JPN'}, 'JE': {'country': 'Jersey', 'code': '44-1534', 'isoCode1': 'JEY'}, 'JO': {'country': 'Jordan', 'code': '962', 'isoCode1': 'JOR'}, 'KZ': {'country': 'Kazakhstan', 'code': '7', 'isoCode1': 'KAZ'}, 'KE': {'country': 'Kenya', 'code': '254', 'isoCode1': 'KEN'}, 'KI': {'country': 'Kiribati', 'code': '686', 'isoCode1': 'KIR'}, 'XK': {'country': 'Kosovo', 'code': '383', 'isoCode1': 'XKX'}, 'KW': {'country': 'Kuwait', 'code': '965', 'isoCode1': 'KWT'}, 'KG': {'country': 'Kyrgyzstan', 'code': '996', 'isoCode1': 'KGZ'}, 'LA': {'country': 'Laos', 'code': '856', 'isoCode1': 'LAO'}, 'LV': {'country': 'Latvia', 'code': '371', 'isoCode1': 'LVA'}, 'LB': {'country': 'Lebanon', 'code': '961', 'isoCode1': 'LBN'}, 'LS': {'country': 'Lesotho', 'code': '266', 'isoCode1': 'LSO'}, 'LR': {'country': 'Liberia', 'code': '231', 'isoCode1': 'LBR'}, 'LY': {'country': 'Libya', 'code': '218', 'isoCode1': 'LBY'}, 'LI': {'country': 'Liechtenstein', 'code': '423', 'isoCode1': 'LIE'}, 'LT': {'country': 'Lithuania', 'code': '370', 'isoCode1': 'LTU'}, 'LU': {'country': 'Luxembourg', 'code': '352', 'isoCode1': 'LUX'}, 'MO': {'country': 'Macau', 'code': '853', 'isoCode1': 'MAC'}, 'MK': {'country': 'Macedonia', 'code': '389', 'isoCode1': 'MKD'}, 'MG': {'country': 'Madagascar', 'code': '261', 'isoCode1': 'MDG'}, 'MW': {'country': 'Malawi', 'code': '265', 'isoCode1': 'MWI'}, 'MY': {'country': 'Malaysia', 'code': '60', 'isoCode1': 'MYS'}, 'MV': {'country': 'Maldives', 'code': '960', 'isoCode1': 'MDV'}, 'ML': {'country': 'Mali', 'code': '223', 'isoCode1': 'MLI'}, 'MT': {'country': 'Malta', 'code': '356', 'isoCode1': 'MLT'}, 'MH': {'country': 'Marshall Islands', 'code': '692', 'isoCode1': 'MHL'}, 'MR': {'country': 'Mauritania', 'code': '222', 'isoCode1': 'MRT'}, 'MU': {'country': 'Mauritius', 'code': '230', 'isoCode1': 'MUS'}, 'YT': {'country': 'Mayotte', 'code': '262', 'isoCode1': 'MYT'}, 'MX': {'country': 'Mexico', 'code': '52', 'isoCode1': 'MEX'}, 'FM': {'country': 'Micronesia', 'code': '691', 'isoCode1': 'FSM'}, 'MD': {'country': 'Moldova', 'code': '373', 'isoCode1': 'MDA'}, 'MC': {'country': 'Monaco', 'code': '377', 'isoCode1': 'MCO'}, 'MN': {'country': 'Mongolia', 'code': '976', 'isoCode1': 'MNG'}, 'ME': {'country': 'Montenegro', 'code': '382', 'isoCode1': 'MNE'}, 'MS': {'country': 'Montserrat', 'code': '1-664', 'isoCode1': 'MSR'}, 'MA': {'country': 'Morocco', 'code': '212', 'isoCode1': 'MAR'}, 'MZ': {'country': 'Mozambique', 'code': '258', 'isoCode1': 'MOZ'}, 'NA': {'country': 'Namibia', 'code': '264', 'isoCode1': 'NAM'}, 'NR': {'country': 'Nauru', 'code': '674', 'isoCode1': 'NRU'}, 'NP': {'country': 'Nepal', 'code': '977', 'isoCode1': 'NPL'}, 'NL': {'country': 'Netherlands', 'code': '31', 'isoCode1': 'NLD'}, 'AN': {'country': 'Netherlands Antilles', 'code': '599', 'isoCode1': 'ANT'}, 'NC': {'country': 'New Caledonia', 'code': '687', 'isoCode1': 'NCL'}, 'NZ': {'country': 'New Zealand', 'code': '64', 'isoCode1': 'NZL'}, 'NI': {'country': 'Nicaragua', 'code': '505', 'isoCode1': 'NIC'}, 'NE': {'country': 'Niger', 'code': '227', 'isoCode1': 'NER'}, 'NG': {'country': 'Nigeria', 'code': '234', 'isoCode1': 'NGA'}, 'NU': {'country': 'Niue', 'code': '683', 'isoCode1': 'NIU'}, 'MP': {'country': 'Northern Mariana Islands', 'code': '1-670', 'isoCode1': 'MNP'}, 'KP': {'country': 'North Korea', 'code': '850', 'isoCode1': 'PRK'}, 'NO': {'country': 'Norway', 'code': '47', 'isoCode1': 'NOR'}, 'OM': {'country': 'Oman', 'code': '968', 'isoCode1': 'OMN'}, 'PK': {'country': 'Pakistan', 'code': '92', 'isoCode1': 'PAK'}, 'PW': {'country': 'Palau', 'code': '680', 'isoCode1': 'PLW'}, 'PS': {'country': 'Palestine', 'code': '970', 'isoCode1': 'PSE'}, 'PA': {'country': 'Panama', 'code': '507', 'isoCode1': 'PAN'}, 'PG': {'country': 'Papua New Guinea', 'code': '675', 'isoCode1': 'PNG'}, 'PY': {'country': 'Paraguay', 'code': '595', 'isoCode1': 'PRY'}, 'PE': {'country': 'Peru', 'code': '51', 'isoCode1': 'PER'}, 'PH': {'country': 'Philippines', 'code': '63', 'isoCode1': 'PHL'}, 'PN': {'country': 'Pitcairn', 'code': '64', 'isoCode1': 'PCN'}, 'PL': {'country': 'Poland', 'code': '48', 'isoCode1': 'POL'}, 'PT': {'country': 'Portugal', 'code': '351', 'isoCode1': 'PRT'}, 'PR': {'country': 'Puerto Rico', 'code': '1-787, 1-939', 'isoCode1': 'PRI'}, 'QA': {'country': 'Qatar', 'code': '974', 'isoCode1': 'QAT'}, 'RE': {'country': 'Reunion', 'code': '262', 'isoCode1': 'REU'}, 'RO': {'country': 'Romania', 'code': '40', 'isoCode1': 'ROU'}, 'RU': {'country': 'Russia', 'code': '7', 'isoCode1': 'RUS'}, 'RW': {'country': 'Rwanda', 'code': '250', 'isoCode1': 'RWA'}, 'BL': {'country': 'Saint Barthelemy', 'code': '590', 'isoCode1': 'BLM'}, 'WS': {'country': 'Samoa', 'code': '685', 'isoCode1': 'WSM'}, 'SM': {'country': 'San Marino', 'code': '378', 'isoCode1': 'SMR'}, 'ST': {'country': 'Sao Tome and Principe', 'code': '239', 'isoCode1': 'STP'}, 'SA': {'country': 'Saudi Arabia', 'code': '966', 'isoCode1': 'SAU'}, 'SN': {'country': 'Senegal', 'code': '221', 'isoCode1': 'SEN'}, 'RS': {'country': 'Serbia', 'code': '381', 'isoCode1': 'SRB'}, 'SC': {'country': 'Seychelles', 'code': '248', 'isoCode1': 'SYC'}, 'SL': {'country': 'Sierra Leone', 'code': '232', 'isoCode1': 'SLE'}, 'SG': {'country': 'Singapore', 'code': '65', 'isoCode1': 'SGP'}, 'SX': {'country': 'Sint Maarten', 'code': '1-721', 'isoCode1': 'SXM'}, 'SK': {'country': 'Slovakia', 'code': '421', 'isoCode1': 'SVK'}, 'SI': {'country': 'Slovenia', 'code': '386', 'isoCode1': 'SVN'}, 'SB': {'country': 'Solomon Islands', 'code': '677', 'isoCode1': 'SLB'}, 'SO': {'country': 'Somalia', 'code': '252', 'isoCode1': 'SOM'}, 'ZA': {'country': 'South Africa', 'code': '27', 'isoCode1': 'ZAF'}, 'KR': {'country': 'South Korea', 'code': '82', 'isoCode1': 'KOR'}, 'SS': {'country': 'South Sudan', 'code': '211', 'isoCode1': 'SSD'}, 'ES': {'country': 'Spain', 'code': '34', 'isoCode1': 'ESP'}, 'LK': {'country': 'Sri Lanka', 'code': '94', 'isoCode1': 'LKA'}, 'SH': {'country': 'Saint Helena', 'code': '290', 'isoCode1': 'SHN'}, 'KN': {'country': 'Saint Kitts and Nevis', 'code': '1-869', 'isoCode1': 'KNA'}, 'LC': {'country': 'Saint Lucia', 'code': '1-758', 'isoCode1': 'LCA'}, 'MF': {'country': 'Saint Martin', 'code': '590', 'isoCode1': 'MAF'}, 'PM': {'country': 'Saint Pierre and Miquelon', 'code': '508', 'isoCode1': 'SPM'}, 'VC': {'country': 'Saint Vincent and the Grenadines', 'code': '1-784', 'isoCode1': 'VCT'}, 'SD': {'country': 'Sudan', 'code': '249', 'isoCode1': 'SDN'}, 'SR': {'country': 'Suriname', 'code': '597', 'isoCode1': 'SUR'}, 'SJ': {'country': 'Svalbard and Jan Mayen', 'code': '47', 'isoCode1': 'SJM'}, 'SZ': {'country': 'Swaziland', 'code': '268', 'isoCode1': 'SWZ'}, 'SE': {'country': 'Sweden', 'code': '46', 'isoCode1': 'SWE'}, 'CH': {'country': 'Switzerland', 'code': '41', 'isoCode1': 'CHE'}, 'SY': {'country': 'Syria', 'code': '963', 'isoCode1': 'SYR'}, 'TW': {'country': 'Taiwan', 'code': '886', 'isoCode1': 'TWN'}, 'TJ': {'country': 'Tajikistan', 'code': '992', 'isoCode1': 'TJK'}, 'TZ': {'country': 'Tanzania', 'code': '255', 'isoCode1': 'TZA'}, 'TH': {'country': 'Thailand', 'code': '66', 'isoCode1': 'THA'}, 'TG': {'country': 'Togo', 'code': '228', 'isoCode1': 'TGO'}, 'TK': {'country': 'Tokelau', 'code': '690', 'isoCode1': 'TKL'}, 'TO': {'country': 'Tonga', 'code': '676', 'isoCode1': 'TON'}, 'TT': {'country': 'Trinidad and Tobago', 'code': '1-868', 'isoCode1': 'TTO'}, 'TN': {'country': 'Tunisia', 'code': '216', 'isoCode1': 'TUN'}, 'TR': {'country': 'Turkey', 'code': '90', 'isoCode1': 'TUR'}, 'TM': {'country': 'Turkmenistan', 'code': '993', 'isoCode1': 'TKM'}, 'TC': {'country': 'Turks and Caicos Islands', 'code': '1-649', 'isoCode1': 'TCA'}, 'TV': {'country': 'Tuvalu', 'code': '688', 'isoCode1': 'TUV'}, 'AE': {'country': 'United Arab Emirates', 'code': '971', 'isoCode1': 'ARE'}, 'UG': {'country': 'Uganda', 'code': '256', 'isoCode1': 'UGA'}, 'GB': {'country': 'United Kingdom', 'code': '44', 'isoCode1': 'GBR'}, 'UA': {'country': 'Ukraine', 'code': '380', 'isoCode1': 'UKR'}, 'UY': {'country': 'Uruguay', 'code': '598', 'isoCode1': 'URY'}, 'US': {'country': 'United States', 'code': '1', 'isoCode1': 'USA'}, 'UZ': {'country': 'Uzbekistan', 'code': '998', 'isoCode1': 'UZB'}, 'VU': {'country': 'Vanuatu', 'code': '678', 'isoCode1': 'VUT'}, 'VA': {'country': 'Vatican', 'code': '379', 'isoCode1': 'VAT'}, 'VE': {'country': 'Venezuela', 'code': '58', 'isoCode1': 'VEN'}, 'VN': {'country': 'Vietnam', 'code': '84', 'isoCode1': 'VNM'}, 'VI': {'country': 'U.S. Virgin Islands', 'code': '1-340', 'isoCode1': 'VIR'}, 'WF': {'country': 'Wallis and Futuna', 'code': '681', 'isoCode1': 'WLF'}, 'EH': {'country': 'Western Sahara', 'code': '212', 'isoCode1': 'ESH'}, 'YE': {'country': 'Yemen', 'code': '967', 'isoCode1': 'YEM'}, 'ZM': {'country': 'Zambia', 'code': '260', 'isoCode1': 'ZMB'}, 'ZW': {'country': 'Zimbabwe', 'code': '263', 'isoCode1': 'ZWE'}}