class Config:
    USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
    BAGGAGE_COLLECTION = [['IDIDBISFL', 'BUSINESS FLEXIBLE', '30 kg'],
                          ['IDIDBISPR', 'BUSINESS PROMO', 'Checked baggage 30kg, cabin baggage 7kg'],
                          ['IDIDECOAF', 'ECO AFFORDABLE', 'Checked baggage 20kg, cabin baggage 7kg'],
                          ['IDIDECOFL', 'ECO FLEXIBLE', '20 kg checked baggage, 7 kg'],
                          ['IDIDECOVL', 'ECO PROMO', 'Checked baggage 20kg, cabin baggage 7kg'],
                          ['WWWWBISFL', 'BUSINESS FLEXIBLE', 'Checked baggage up to 40kg, cabin baggage 7kg'],
                          ['WWWWBISPR', 'BUSINESS PROMO', 'Checked baggage up to 40kg, cabin baggage 7kg'],
                          ['WWWWBISPR', 'BUSINESS PROMO', '40 kg'],
                          ['WWWWECOAF', 'ECO AFFORDABLE', 'Checked baggage up to 30kg, cabin baggage 7kg'],
                          ['WWWWECOFL', 'ECO FLEXIBLE', 'Checked baggage up to 30kg, cabin baggage 7kg'],
                          ['WWWWECOPR', 'ECO SPECIAL PROMO', '30 kg'],
                          ['WWWWECOVL', 'ECO PROMO', 'Checked baggage up to 30kg, cabin baggage 7kg'],
                          ['WWWWFIRFL', 'FIRST CLASS', 'Checked baggage 50kg, cabin baggage 7kg'],
                          ['WWWWFIRPR', 'FIRST CLASS PROMO', 'Checked baggage 50kg, cabin baggage 7kg'],
                          ['IDIDECOPR', 'ECO SPECIAL PROMO', '20 kg checked baggage, 7 kg cabin baggage'],
                          ['IDIDBISAF', 'BUSINESS AFFORDABLE', 'Checked baggage 30kg, cabin baggage 7kg'],
                          ['IDIDBISCF', 'BUSINESS COMFORT', 'Checked baggage 30kg, cabin baggage 7kg'],
                          ['IDIDECOCF', 'ECO COMFORT', 'Checked baggage 20kg, cabin baggage 7kg'],
                          ['IDIDFIRCF', 'FIRST COMFORT', 'Checked baggage 50kg, cabin baggage 7kg']]
    OPERATING_FLIGHT_NUMBER_MAP = {
        'GA8700': 'QG400',
        'GA8701': 'QG401',
        'GA8702': 'QG974',
        'GA8703': 'QG975',
        'GA8710': 'QG438',
        'GA8711': 'QG439',
        'GA8724': 'QG602',
        'GA8725': 'QG331',
        'GA8726': 'QG330',
        'GA8727': 'QG603',
        'GA8736': 'QG452',
        'GA8737': 'QG453',
        'GA8738': 'QG938',
        'GA8739': 'QG939',
        'GA8744': 'QG482',
        'GA8745': 'QG483',
        'GA8747': 'QG447',
        'GA8750': 'QG792',
        'GA8792': 'QG976',
        'GA8793': 'QG977',
        'GA8800': 'QG416',
        'GA8802': 'QG210',
        'GA8803': 'QG211',
        'GA8805': 'QG343',
        'GA8712': 'QG424',
        'GA8751': 'QG793',
        'GA8804': 'QG342',
    }
