

class Config:
    # USER_AGENT = f"Mozilla/5.0 (Linux; Android {random.randint(9, 13)}; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/{random.randint(131, 140)}.0.{random.randint(1111, 9999)}.{random.randint(111, 999)} Mobile Safari/537.36"
    #  USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36"
    USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"
    ACCEPT_LANGUAGE = "en-US,en;q=0.9"
    CCAVENUE_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"
    CCAVENUE_ACCEPT_LANGUAGE = "en-US,en;q=0.9"
    CCAVENUE_RSA_KEY = (
        "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC3aQBAGvFdZE0vj/6YGMPa0jXwNZshINXUl/"
        "iMJp37eYPnsFzwhhUSQmF7uH2XOclZpV73pk2zeZQIL7NvLkap7b8dMpLfhlyCwadB/"
        "v7UimeECBRoABnEzWIxVE+9LeJhkmdrJNhl50bOx5i9FTCz3eF2a32MUFFJlCQ8prhySQIDAQAB"
    )
    CCAVENUE_BROWSER_DATA = (
        "&screenHeight=1169&screenWidth=1800&colorDepth=30&javaEnabled=false"
        "&timeZone=-480&browserLanguage=zh-CN"
    )
    AIRPORTS = {
        "data": [
            {
                "country": "Australia",
                "country_kr": "호주",
                "countryCode": "AU",
                "cityName": "Adelaide",
                "cityName_kr": "애들레이드",
                "cityCode": "ADL",
                "airportCode": "ADL",
                "gmt": "+10:00",
                "currency": "AUD"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Alor Island",
                "cityName_kr": "알로르섬",
                "cityCode": "ARD",
                "airportCode": "ARD",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Ambon",
                "cityName_kr": "암본",
                "cityCode": "AMQ",
                "airportCode": "AMQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "India",
                "country_kr": "인도",
                "countryCode": "IN",
                "cityName": "Amritsar",
                "cityName_kr": "암리차르",
                "cityCode": "ATQ",
                "airportCode": "ATQ",
                "gmt": "+5:30",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Anambas  ",
                "cityName_kr": "아남바스",
                "cityCode": "LMU",
                "airportCode": "LMU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Atambua",
                "cityName_kr": "아탐부아",
                "cityCode": "ABU",
                "airportCode": "ABU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Bajawa",
                "cityName_kr": "바자와",
                "cityCode": "BJW",
                "airportCode": "BJW",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Bali",
                "cityName_kr": "발리",
                "cityCode": "DPS",
                "airportCode": "DPS",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Balikpapan",
                "cityName_kr": "발릭파판",
                "cityCode": "BPN",
                "airportCode": "BPN",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Banda Aceh",
                "cityName_kr": "반다아체",
                "cityCode": "BTJ",
                "airportCode": "BTJ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Bandar Lampung",
                "cityName_kr": "반다르 람풍",
                "cityCode": "TKG",
                "airportCode": "TKG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Bandung",
                "cityName_kr": "반둥",
                "cityCode": "BDO",
                "airportCode": "BDO",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "India",
                "country_kr": "인도",
                "countryCode": "IN",
                "cityName": "Bangalore",
                "cityName_kr": "방갈로르",
                "cityCode": "BLR",
                "airportCode": "BLR",
                "gmt": "+5:30",
                "currency": "IDR"
            },
            {
                "country": "Thailand",
                "country_kr": "태국",
                "countryCode": "TH",
                "cityName": "Bangkok",
                "cityName_kr": "방콕",
                "cityCode": "DMK",
                "airportCode": "DMK",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Banjarmasin",
                "cityName_kr": "반자르마신",
                "cityCode": "BDJ",
                "airportCode": "BDJ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Banyuwangi",
                "cityName_kr": "반유왕이",
                "cityCode": "BWX",
                "airportCode": "BWX",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Batam",
                "cityName_kr": "바탐",
                "cityCode": "BTH",
                "airportCode": "BTH",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Batu Licin",
                "cityName_kr": "바뚜리친",
                "cityCode": "BTW",
                "airportCode": "BTW",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Baubau",
                "cityName_kr": "바우바우",
                "cityCode": "BUW",
                "airportCode": "BUW",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Bengkulu",
                "cityName_kr": "벵쿨루",
                "cityCode": "BKS",
                "airportCode": "BKS",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Berau",
                "cityName_kr": "베라우",
                "cityCode": "BEJ",
                "airportCode": "BEJ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Bima",
                "cityName_kr": "비마",
                "cityCode": "BMU",
                "airportCode": "BMU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Australia",
                "country_kr": "호주",
                "countryCode": "AU",
                "cityName": "Brisbane",
                "cityName_kr": "브리즈번",
                "cityCode": "BNE",
                "airportCode": "BNE",
                "gmt": "+10:00",
                "currency": "AUD"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Buli",
                "cityName_kr": "불리",
                "cityCode": "WUB",
                "airportCode": "WUB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Buol",
                "cityName_kr": "부올",
                "cityCode": "UOL",
                "airportCode": "UOL",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Changsha",
                "cityName_kr": "창사",
                "cityCode": "CSX",
                "airportCode": "CSX",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Chengdu",
                "cityName_kr": "청두",
                "cityCode": "TFU",
                "airportCode": "TFU",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "India",
                "country_kr": "인도",
                "countryCode": "IN",
                "cityName": "Chennai",
                "cityName_kr": "첸나이",
                "cityCode": "MAA",
                "airportCode": "MAA",
                "gmt": "+5:30",
                "currency": "IDR"
            },
            {
                "country": "Thailand",
                "country_kr": "태국",
                "countryCode": "TH",
                "cityName": "Chiang Mai",
                "cityName_kr": "치앙마이",
                "cityCode": "CNX",
                "airportCode": "CNX",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Thailand",
                "country_kr": "태국",
                "countryCode": "TH",
                "cityName": "Chiang Rai",
                "cityName_kr": "치앙라이",
                "cityCode": "CEI",
                "airportCode": "CEI",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Chongqing",
                "cityName_kr": "충칭",
                "cityCode": "CKG",
                "airportCode": "CKG",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Cilacap",
                "cityName_kr": "칠라차프",
                "cityCode": "CXP",
                "airportCode": "CXP",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Vietnam",
                "country_kr": "베트남",
                "countryCode": "VN",
                "cityName": "Da Nang",
                "cityName_kr": "다낭",
                "cityCode": "DAD",
                "airportCode": "DAD",
                "gmt": "GMT",
                "currency": "USD"
            },
            {
                "country": "India",
                "country_kr": "인도",
                "countryCode": "IN",
                "cityName": "Delhi",
                "cityName_kr": "델리",
                "cityCode": "DEL",
                "airportCode": "DEL",
                "gmt": "+5:30",
                "currency": "IDR"
            },
            {
                "country": "Bangladesh",
                "country_kr": "방글라데시",
                "countryCode": "BD",
                "cityName": "Dhaka",
                "cityName_kr": "다카",
                "cityCode": "DAC",
                "airportCode": "DAC",
                "gmt": "GMT",
                "currency": "BDT"
            },
            {
                "country": "Maldives",
                "country_kr": "몰디브",
                "countryCode": "MV",
                "cityName": "Male",
                "cityName_kr": "말레 ",
                "cityCode": "MLE",
                "airportCode": "MLE",
                "gmt": "+4:00",
                "currency": "USD"
            },
            {
                "country": "United Arab Emirates",
                "country_kr": "아랍에미리트",
                "countryCode": "AE",
                "cityName": "Dubai",
                "cityName_kr": "두바이",
                "cityCode": "DXB",
                "airportCode": "DXB",
                "gmt": "+4:00",
                "currency": "AED"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Dobo",
                "cityName_kr": "도보",
                "cityCode": "DOB",
                "airportCode": "DOB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Dumai",
                "cityName_kr": "두마이",
                "cityCode": "DUM",
                "airportCode": "DUM",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Ende",
                "cityName_kr": "엔데",
                "cityCode": "ENE",
                "airportCode": "ENE",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Fak Fak",
                "cityName_kr": "팍팍",
                "cityCode": "FKQ",
                "airportCode": "FKQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Galela",
                "cityName_kr": "갈렐라",
                "cityCode": "GLX",
                "airportCode": "GLX",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Gorontalo",
                "cityName_kr": "고론탈로",
                "cityCode": "GTO",
                "airportCode": "GTO",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Guangzhou",
                "cityName_kr": "광저우",
                "cityCode": "CAN",
                "airportCode": "CAN",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Guilin",
                "cityName_kr": "계림",
                "cityCode": "KWL",
                "airportCode": "KWL",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Guiyang",
                "cityName_kr": "구이양",
                "cityCode": "KWE",
                "airportCode": "KWE",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Gunungsitoli",
                "cityName_kr": "구눙시톨리",
                "cityCode": "GNS",
                "airportCode": "GNS",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Haikou",
                "cityName_kr": "하이커우",
                "cityCode": "HAK",
                "airportCode": "HAK",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "Vietnam",
                "country_kr": "베트남",
                "countryCode": "VN",
                "cityName": "Hanoi",
                "cityName_kr": "하노이",
                "cityCode": "HAN",
                "airportCode": "HAN",
                "gmt": "GMT",
                "currency": "USD"
            },
            {
                "country": "Thailand",
                "country_kr": "태국",
                "countryCode": "TH",
                "cityName": "Hat Yai",
                "cityName_kr": "핫야이",
                "cityCode": "HDY",
                "airportCode": "HDY",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Hong Kong",
                "country_kr": "홍콩",
                "countryCode": "HK",
                "cityName": "Hong Kong",
                "cityName_kr": "홍콩",
                "cityCode": "HKG",
                "airportCode": "HKG",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Turkey",
                "country_kr": "터키",
                "countryCode": "TR",
                "cityName": "Istanbul",
                "cityName_kr": "이스탄불",
                "cityCode": "IST",
                "airportCode": "IST",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Jakarta",
                "cityName_kr": "자카르타",
                "cityCode": "CGK",
                "airportCode": "CGK",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Halim, Jakarta",
                "cityName_kr": "자카르타",
                "cityCode": "HLP",
                "airportCode": "HLP",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Jambi",
                "cityName_kr": "잠비",
                "cityCode": "DJB",
                "airportCode": "DJB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Jayapura",
                "cityName_kr": "자야푸라",
                "cityCode": "DJJ",
                "airportCode": "DJJ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Saudi Arabia",
                "country_kr": "사우디 아라비아",
                "countryCode": "SA",
                "cityName": "Jeddah",
                "cityName_kr": "제다",
                "cityCode": "JED",
                "airportCode": "JED",
                "gmt": "+2:30",
                "currency": "SAR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Jember",
                "cityName_kr": "젬버",
                "cityCode": "JBB",
                "airportCode": "JBB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Johor Bahru",
                "cityName_kr": "조호르바루",
                "cityCode": "JHB",
                "airportCode": "JHB",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Kaimana",
                "cityName_kr": "카이마나",
                "cityCode": "KNG",
                "airportName": "\n",
                "airportCode": "KNG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Nepal",
                "country_kr": "네팔",
                "countryCode": "NP",
                "cityName": "Kathmandu",
                "cityName_kr": "카트만두",
                "cityCode": "KTM",
                "airportCode": "KTM",
                "gmt": "GMT",
                "currency": "USD"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Kendari",
                "cityName_kr": "켄다리",
                "cityCode": "KDI",
                "airportCode": "KDI",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Kerinci",
                "cityName_kr": "케린치",
                "cityCode": "KRC",
                "airportCode": "KRC",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Ketapang",
                "cityName_kr": "케타팡",
                "cityCode": "KTG",
                "airportCode": "KTG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "India",
                "country_kr": "인도",
                "countryCode": "IN",
                "cityName": "Kochi",
                "cityName_kr": "코치",
                "cityCode": "COK",
                "airportCode": "COK",
                "gmt": "+5:30",
                "currency": "IDR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Kota Bharu",
                "cityName_kr": "코타바루",
                "cityCode": "KBR",
                "airportCode": "KBR",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Kota Kinabalu",
                "cityName_kr": "코타키나발루",
                "cityCode": "BKI",
                "airportCode": "BKI",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Kotabaru",
                "cityName_kr": "코타바루",
                "cityCode": "KBU",
                "airportCode": "KBU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Thailand",
                "country_kr": "태국",
                "countryCode": "TH",
                "cityName": "Krabi",
                "cityName_kr": "크라비",
                "cityCode": "KBV",
                "airportCode": "KBV",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Kuala Lumpur",
                "cityName_kr": "쿠알라룸푸르",
                "cityCode": "KUL",
                "airportCode": "KUL",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Sibu",
                "cityName_kr": "시부",
                "cityCode": "SBW",
                "airportCode": "SBW",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Kuching",
                "cityName_kr": "쿠칭",
                "cityCode": "KCH",
                "airportCode": "KCH",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Kunming",
                "cityName_kr": "쿤밍",
                "cityCode": "KMG",
                "airportCode": "KMG",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Kupang",
                "cityName_kr": "쿠팡",
                "cityCode": "KOE",
                "airportCode": "KOE",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Tawau",
                "cityName_kr": "타와우",
                "cityCode": "TWU",
                "airportCode": "TWU",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Labuha",
                "cityName_kr": "라부하",
                "cityCode": "LAH",
                "airportCode": "LAH",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Labuan Bajo",
                "cityName_kr": "라부안 바조",
                "cityCode": "LBJ",
                "airportCode": "LBJ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Pakistan",
                "country_kr": "파키스탄",
                "countryCode": "PK",
                "cityName": "Lahore",
                "cityName_kr": "라호르",
                "cityCode": "LHE",
                "airportCode": "LHE",
                "gmt": "5",
                "currency": "USD"
            },
            {
                "country": "Pakistan",
                "country_kr": "파키스탄",
                "countryCode": "PK",
                "cityName": "Karachi",
                "cityName_kr": "카라치",
                "cityCode": "KHI",
                "airportCode": "KHI",
                "gmt": "5",
                "currency": "USD"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Langkawi",
                "cityName_kr": "랑카위",
                "cityCode": "LGK",
                "airportCode": "LGK",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Larantuka",
                "cityName_kr": "라란투카",
                "cityCode": "LKA",
                "airportCode": "LKA",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Lhokseumawe",
                "cityName_kr": "록세우마웨",
                "cityCode": "LSW",
                "airportCode": "LSW",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Lombok",
                "cityName_kr": "롬복",
                "cityCode": "LOP",
                "airportCode": "LOP",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Lubuk Linggau",
                "cityName_kr": "루북 링가우",
                "cityCode": "LKI",
                "airportCode": "LKI",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Luwuk",
                "cityName_kr": "루욱",
                "cityCode": "LUW",
                "airportCode": "LUW",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Macau",
                "country_kr": "마카오",
                "countryCode": "MO",
                "cityName": "Macau",
                "cityName_kr": "마카오",
                "cityCode": "MFM",
                "airportCode": "MFM",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Saudi Arabia",
                "country_kr": "사우디 아라비아",
                "countryCode": "SA",
                "cityName": "Medina",
                "cityName_kr": "메디나",
                "cityCode": "MED",
                "airportCode": "MED",
                "gmt": "+2:30",
                "currency": "SAR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Majalengka",
                "cityName_kr": "마잘렝카",
                "cityCode": "KJT",
                "airportCode": "KJT",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Malang",
                "cityName_kr": "말랑",
                "cityCode": "MLG",
                "airportCode": "MLG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Malinau",
                "cityName_kr": "말리나우",
                "cityCode": "MWW",
                "airportCode": "MWW",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Mamuju",
                "cityName_kr": "마무주",
                "cityCode": "MJU",
                "airportCode": "MJU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Manado",
                "cityName_kr": "마나도",
                "cityCode": "MDC",
                "airportCode": "MDC",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Manokwari",
                "cityName_kr": "마노크와리",
                "cityCode": "MKW",
                "airportCode": "MKW",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Mataram",
                "cityName_kr": "마타람",
                "cityCode": "AMI",
                "airportCode": "AMI",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Maumere",
                "cityName_kr": "마우메레",
                "cityCode": "MOF",
                "airportCode": "MOF",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Mckenna AAF",
                "cityName_kr": "맥케나 AAF",
                "cityCode": "MKF",
                "airportCode": "MKF",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Medan",
                "cityName_kr": "메단",
                "cityCode": "MES",
                "airportCode": "MES",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Medan Kuala Namu",
                "cityName_kr": "메단 쿠알라나무",
                "cityCode": "KNO",
                "airportCode": "KNO",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Melanguane ",
                "cityName_kr": "멜랑구안",
                "cityCode": "MNA",
                "airportCode": "MNA",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Australia",
                "country_kr": "호주",
                "countryCode": "AU",
                "cityName": "Melbourne",
                "cityName_kr": "멜버른",
                "cityCode": "MEL",
                "airportCode": "MEL",
                "gmt": "+10:00",
                "currency": "AUD"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Merauke",
                "cityName_kr": "메라우케",
                "cityCode": "MKQ",
                "airportCode": "MKQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Meulaboh",
                "cityName_kr": "믈라보",
                "cityCode": "MEQ",
                "airportCode": "MEQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Morotai",
                "cityName_kr": "모로타이",
                "cityCode": "OTI",
                "airportCode": "OTI",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Morowali",
                "cityName_kr": "모로왈리",
                "cityCode": "MOH",
                "airportCode": "MOH",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Muko-Muko",
                "cityName_kr": "무코무코",
                "cityCode": "MPC",
                "airportCode": "MPC",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "India",
                "country_kr": "인도",
                "countryCode": "IN",
                "cityName": "Mumbai",
                "cityName_kr": "뭄바이",
                "cityCode": "BOM",
                "airportCode": "BOM",
                "gmt": "+5:30",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Nabire",
                "cityName_kr": "나비레",
                "cityCode": "NBX",
                "airportCode": "NBX",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Japan",
                "country_kr": "일본",
                "countryCode": "JP",
                "cityName": "Nagoya",
                "cityName_kr": "나고야",
                "cityCode": "NGO",
                "airportCode": "NGO",
                "gmt": "GMT",
                "currency": "JPY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Namlea",
                "cityName_kr": "남레아",
                "cityCode": "NAM",
                "airportCode": "NAM",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Nanchang",
                "cityName_kr": "난창",
                "cityCode": "KHN",
                "airportCode": "KHN",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Nanning",
                "cityName_kr": "난닝",
                "cityCode": "NNG",
                "airportCode": "NNG",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Natuna Ranai",
                "cityName_kr": "나투나 라나이",
                "cityCode": "NTX",
                "airportCode": "NTX",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Japan",
                "country_kr": "일본",
                "countryCode": "JP",
                "cityName": "Osaka",
                "cityName_kr": "오사카",
                "cityCode": "KIX",
                "airportCode": "KIX",
                "gmt": "GMT",
                "currency": "JPY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Padang",
                "cityName_kr": "파당",
                "cityCode": "PDG",
                "airportCode": "PDG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Padang Sidempuan",
                "cityName_kr": "파당 시덴푸안",
                "cityCode": "AEG",
                "airportCode": "AEG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Pagar Alam",
                "cityName_kr": "파가르 알람",
                "cityCode": "PXA",
                "airportCode": "PXA",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Palangkaraya",
                "cityName_kr": "팔랑카라야",
                "cityCode": "PKY",
                "airportCode": "PKY",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Palembang",
                "cityName_kr": "팔렘방",
                "cityCode": "PLM",
                "airportCode": "PLM",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Palopo",
                "cityName_kr": "팔로포",
                "cityCode": "LLO",
                "airportCode": "LLO",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Palu",
                "cityName_kr": "팔루",
                "cityCode": "PLW",
                "airportCode": "PLW",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Pangkal Pinang",
                "cityName_kr": "팡칼 피낭",
                "cityCode": "PGK",
                "airportCode": "PGK",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Pangkalan Bun",
                "cityName_kr": "팡카란 분",
                "cityCode": "PKN",
                "airportCode": "PKN",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Pekanbaru",
                "cityName_kr": "페칸바루",
                "cityCode": "PKU",
                "airportCode": "PKU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Penang",
                "cityName_kr": "페낭",
                "cityCode": "PEN",
                "airportCode": "PEN",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Australia",
                "country_kr": "호주",
                "countryCode": "AU",
                "cityName": "Perth",
                "cityName_kr": "퍼스",
                "cityCode": "PER",
                "airportCode": "PER",
                "gmt": "+10:00",
                "currency": "AUD"
            },
            {
                "country": "Thailand",
                "country_kr": "태국",
                "countryCode": "TH",
                "cityName": "Phuket",
                "cityName_kr": "푸켓",
                "cityCode": "HKT",
                "airportCode": "HKT",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Pomalaa",
                "cityName_kr": "포말라아",
                "cityCode": "PUM",
                "airportCode": "PUM",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Pontianak",
                "cityName_kr": "폰티아낙",
                "cityCode": "PNK",
                "airportCode": "PNK",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Poso",
                "cityName_kr": "포소",
                "cityCode": "PSJ",
                "airportCode": "PSJ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Putus Sibau",
                "cityName_kr": "부투스 시바우",
                "cityCode": "PSU",
                "airportCode": "PSU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Raha",
                "cityName_kr": "라하",
                "cityCode": "RAQ",
                "airportCode": "RAQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Rengat",
                "cityName_kr": "렌가트",
                "cityCode": "RGT",
                "airportCode": "RGT",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Roti",
                "cityName_kr": "로티",
                "cityCode": "RTI",
                "airportCode": "RTI",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "countryCode": "TL",
                "cityName": "Maimun Saleh Airport",
                "cityCode": "SBG",
                "airportCode": "SBG",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Samarinda",
                "cityName_kr": "사마린다",
                "cityCode": "SRI",
                "airportCode": "SRI",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Sampit",
                "cityName_kr": "삼핏",
                "cityCode": "SMQ",
                "airportCode": "SMQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Sanana",
                "cityName_kr": "사나나",
                "cityCode": "SQN",
                "airportCode": "SQN",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Sandakan",
                "cityName_kr": "산다칸",
                "cityCode": "SDK",
                "airportCode": "SDK",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Saumlaki",
                "cityName_kr": "사움라키",
                "cityCode": "SXK",
                "airportCode": "SXK",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Semarang",
                "cityName_kr": "세마랑",
                "cityCode": "SRG",
                "airportCode": "SRG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "South Korea",
                "country_kr": "대한민국",
                "countryCode": "KR",
                "cityName": "Seoul",
                "cityName_kr": "서울",
                "cityCode": "ICN",
                "airportCode": "ICN",
                "gmt": "+9:00",
                "currency": "KRW"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Sibolga",
                "cityName_kr": "시볼가",
                "cityCode": "FLZ",
                "airportCode": "FLZ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Silangit ",
                "cityName_kr": "실랑잇",
                "cityCode": "DTB",
                "airportCode": "DTB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Simeulue",
                "cityName_kr": "시메울루에",
                "cityCode": "SMG",
                "airportCode": "SMG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Singapore",
                "country_kr": "싱가포르",
                "countryCode": "SG",
                "cityName": "Singapore",
                "cityName_kr": "싱가포르",
                "cityCode": "SIN",
                "airportCode": "SIN",
                "gmt": "+8:00",
                "currency": "SGD"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Sintang",
                "cityName_kr": "신탕",
                "cityCode": "SQG",
                "airportCode": "SQG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Solo",
                "cityName_kr": "솔로",
                "cityCode": "SOC",
                "airportCode": "SOC",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Sorong",
                "cityName_kr": "밀다",
                "cityCode": "SOQ",
                "airportCode": "SOQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Sumbawa",
                "cityName_kr": "숨바와",
                "cityCode": "SWQ",
                "airportCode": "SWQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Sumenep",
                "cityName_kr": "수메넵",
                "cityCode": "SUP",
                "airportCode": "SUP",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Surabaya",
                "cityName_kr": "수라바야",
                "cityCode": "SUB",
                "airportCode": "SUB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Thailand",
                "country_kr": "태국",
                "countryCode": "TH",
                "cityName": "Surat Thani",
                "cityName_kr": "수랏타니",
                "cityCode": "URT",
                "airportCode": "URT",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Australia",
                "country_kr": "호주",
                "countryCode": "AU",
                "cityName": "Sydney",
                "cityName_kr": "시드니",
                "cityCode": "SYD",
                "airportCode": "SYD",
                "gmt": "+10:00",
                "currency": "AUD"
            },
            {
                "country": "Australia",
                "country_kr": "호주",
                "countryCode": "AU",
                "cityName": "Canberra",
                "cityName_kr": "캔버라",
                "cityCode": "CBR",
                "airportCode": "CBR",
                "gmt": "+10:00",
                "currency": "AUD"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tahuna",
                "cityName_kr": "타후나",
                "cityCode": "NAH",
                "airportCode": "NAH",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Taiwan",
                "country_kr": "대만",
                "countryCode": "TW",
                "cityName": "Taipei",
                "cityName_kr": "타이페이",
                "cityCode": "TPE",
                "airportCode": "TPE",
                "gmt": "+7:00",
                "currency": "TWD"
            },
            {
                "country": "Taiwan",
                "country_kr": "대만",
                "countryCode": "TW",
                "cityName": "Kaohsiung",
                "cityName_kr": "가오슝",
                "cityCode": "KHH",
                "airportCode": "KHH",
                "gmt": "+7:00",
                "currency": "TWD"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Takengon",
                "cityName_kr": "타켄곤",
                "cityCode": "TXE",
                "airportCode": "TXE",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tambolaka",
                "cityName_kr": "탐볼라카",
                "cityCode": "TMC",
                "airportCode": "TMC",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tanjung",
                "cityName_kr": "탄중",
                "cityCode": "TJG",
                "airportCode": "TJG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tanjung Pandan",
                "cityName_kr": "탄중판단",
                "cityCode": "TJQ",
                "airportCode": "TJQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tanjung Pinang",
                "cityName_kr": "탄중 피낭",
                "cityCode": "TNJ",
                "airportCode": "TNJ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tanjung Selor",
                "cityName_kr": "탄중슬로르",
                "cityCode": "TJS",
                "airportCode": "TJS",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tarakan",
                "cityName_kr": "타라칸",
                "cityCode": "TRK",
                "airportCode": "TRK",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tasikmalaya",
                "cityName_kr": "타시크말라야",
                "cityCode": "TSY",
                "airportCode": "TSY",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Ternate",
                "cityName_kr": "테르나테",
                "cityCode": "TTE",
                "airportCode": "TTE",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Tianjin",
                "cityName_kr": "톈진",
                "cityCode": "TSN",
                "airportCode": "TSN",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Timika",
                "cityName_kr": "티미카",
                "cityCode": "TIM",
                "airportCode": "TIM",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "India",
                "country_kr": "인도",
                "countryCode": "IN",
                "cityName": "Tiruchirapally",
                "cityName_kr": "티추리라팔리 ",
                "cityCode": "TRZ",
                "airportCode": "TRZ",
                "gmt": "+5:30",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tobelo",
                "cityName_kr": "토벨로",
                "cityCode": "KAZ",
                "airportCode": "KAZ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Japan",
                "country_kr": "일본",
                "countryCode": "JP",
                "cityName": "Tokyo",
                "cityName_kr": "도쿄",
                "cityCode": "NRT",
                "airportCode": "NRT",
                "gmt": "+9:00",
                "currency": "JPY"
            },
            {
                "country": "Japan",
                "country_kr": "일본",
                "countryCode": "JP",
                "cityName": "Okinawa",
                "cityName_kr": "오키나와",
                "cityCode": "OKA",
                "airportCode": "OKA",
                "gmt": "+9:00",
                "currency": "JPY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Toli-Toli",
                "cityName_kr": "톨리톨리",
                "cityCode": "TLI",
                "airportCode": "TLI",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tual",
                "cityName_kr": "투알",
                "cityCode": "LUV",
                "airportCode": "LUV",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Thailand",
                "country_kr": "태국",
                "countryCode": "TH",
                "cityName": "Udon Thani",
                "cityName_kr": "우돈타니",
                "cityCode": "UTH",
                "airportCode": "UTH",
                "gmt": "GMT",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Makassar",
                "cityName_kr": "마카사르",
                "cityCode": "UPG",
                "airportCode": "UPG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Waingapu",
                "cityName_kr": "와잉아푸",
                "cityCode": "WGP",
                "airportCode": "WGP",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Wakatobi",
                "cityName_kr": "와카토비",
                "cityCode": "WNI",
                "airportCode": "WNI",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Wamena",
                "cityName_kr": "와메나",
                "cityCode": "WMX",
                "airportCode": "WMX",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "China",
                "countryCode": "CN",
                "cityName": "Wuhan",
                "cityName_kr": "우한",
                "cityCode": "WUH",
                "airportCode": "WUH",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Yahukimo",
                "cityName_kr": "야후키모",
                "cityCode": "DEX",
                "airportCode": "DEX",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Yogyakarta",
                "cityName_kr": "족자카르타",
                "cityCode": "YIA",
                "airportCode": "YIA",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Zhengzhou",
                "cityName_kr": "정저우",
                "cityCode": "CGO",
                "airportCode": "CGO",
                "gmt": "GMT",
                "currency": "CNY"
            },
            {
                "country": "Uzbekistan",
                "country_kr": "우즈베키스탄",
                "countryCode": "UZ",
                "cityName": "Tashkent",
                "cityName_kr": "타슈켄트",
                "cityCode": "TAS",
                "airportCode": "TAS",
                "gmt": "+05:00",
                "currency": "USD"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Zhangjiajie",
                "cityName_kr": "장가계",
                "cityCode": "DYG",
                "airportCode": "DYG",
                "gmt": "+7:00",
                "currency": "CNY"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Subang",
                "cityName_kr": "수방",
                "cityCode": "SZB",
                "airportCode": "SZB",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Alor Setar",
                "cityName_kr": "알로르 세타르",
                "cityCode": "AOR",
                "airportName": "Alor Setar",
                "airportCode": "AOR",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Ordos",
                "cityName_kr": "오르도스",
                "cityCode": "DSN",
                "airportName": "DSN",
                "airportCode": "DSN",
                "gmt": "+8;00",
                "currency": "CNY"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Bintulu",
                "cityName_kr": "빈툴루",
                "cityCode": "BTU",
                "airportName": "Bintulu Airport",
                "airportCode": "BTU",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "China",
                "country_kr": "중국",
                "countryCode": "CN",
                "cityName": "Qionghai",
                "cityName_kr": "충하이",
                "cityCode": "BAR",
                "airportName": "Qionghai Bo'ao International Airport",
                "airportCode": "BAR",
                "gmt": "+8:00",
                "currency": "CNY"
            },
            {
                "country": "Malaysia",
                "country_kr": "말레이시아",
                "countryCode": "MY",
                "cityName": "Miri",
                "cityName_kr": "미리",
                "cityCode": "MYY",
                "airportName": "Miri",
                "airportCode": "MYY",
                "gmt": "+8:00",
                "currency": "MYR"
            },
            {
                "country": "Thailand",
                "countryCode": "TH",
                "cityName": "Phitsanulok",
                "cityCode": "PHS",
                "airportName": "Phitsanulok",
                "airportCode": "PHS",
                "gmt": "+7:00",
                "currency": "THB"
            },
            {
                "country": "Thailand",
                "countryCode": "TH",
                "cityName": "Ubon Ratchathani",
                "cityCode": "UBP",
                "airportName": "Ubon Ratchathani",
                "airportCode": "UBP",
                "gmt": "+7:00",
                "currency": "THB"
            },
            {
                "country": "Thailand",
                "countryCode": "TH",
                "cityName": "Khon Kaen",
                "cityCode": "KKC",
                "airportName": "Khon Kaen",
                "airportCode": "KKC",
                "gmt": "+7:00",
                "currency": "THB"
            },
            {
                "country": "Thailand",
                "countryCode": "TH",
                "cityName": "Nakhon Si Thammarat",
                "cityCode": "NST",
                "airportName": "Nakhon Si Thammarat",
                "airportCode": "NST",
                "gmt": "+7:00",
                "currency": "THB"
            },
            {
                "country": "Thailand",
                "countryCode": "TH",
                "cityName": "Trang",
                "cityCode": "TST",
                "airportName": "Trang",
                "airportCode": "TST",
                "gmt": "+7:00",
                "currency": "THB"
            },
            {
                "country": "Thailand",
                "countryCode": "TH",
                "cityName": "U Tapao",
                "cityCode": "UTP",
                "airportName": "U Tapao",
                "airportCode": "UTP",
                "gmt": "+7:00",
                "currency": "THB"
            },
            {
                "country": "China",
                "countryCode": "CN",
                "cityName": "Hangzhou",
                "cityCode": "HGH",
                "airportName": "Hangzhou",
                "airportCode": "HGH",
                "gmt": "+8:00",
                "currency": "CNY"
            },
            {
                "country": "China",
                "countryCode": "CN",
                "cityName": "Shenzhen",
                "cityCode": "SZX",
                "airportName": "Shenzhen",
                "airportCode": "SZX",
                "gmt": "+8:00",
                "currency": "CNY"
            },
            {
                "country": "China",
                "countryCode": "CN",
                "cityName": "Xi'an",
                "cityCode": "XIY",
                "airportName": "Xi'an",
                "airportCode": "XIY",
                "gmt": "+8:00",
                "currency": "CNY"
            },
            {
                "country": "China",
                "countryCode": "CN",
                "cityName": "Shanghai",
                "cityCode": "PVG",
                "airportName": "Shanghai",
                "airportCode": "PVG",
                "gmt": "+8:00",
                "currency": "CNY"
            },
            {
                "country": "India",
                "country_kr": "인도",
                "countryCode": "IN",
                "cityName": "Ahmedabad",
                "cityCode": "AMD",
                "airportName": "Ahmedabad",
                "airportCode": "AMD",
                "gmt": "+5:30",
                "currency": "INR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Samarinda",
                "cityCode": "AAP",
                "airportCode": "AAP",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Baik",
                "cityCode": "BIK",
                "airportCode": "BIK",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Siau",
                "cityCode": "BRG",
                "airportCode": "BRG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Babo",
                "cityCode": "BXB",
                "airportCode": "BXB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Penggung",
                "cityCode": "CBN",
                "airportCode": "CBN",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Kediri",
                "cityCode": "DHX",
                "airportCode": "DHX",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Asmat",
                "cityCode": "EWE",
                "airportCode": "EWE",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "West Kutai",
                "cityCode": "GHS",
                "airportCode": "GHS",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Muara Teweh",
                "cityCode": "HMS",
                "airportCode": "HMS",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Pomalaa",
                "cityCode": "KXB",
                "airportCode": "KXB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Lubuk Linggau",
                "cityCode": "LLJ",
                "airportCode": "LLJ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Malinau",
                "cityCode": "LNU",
                "airportCode": "LNU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Lewoleba",
                "cityCode": "LWE",
                "airportCode": "LWE",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Morowali",
                "cityCode": "MWS",
                "airportName": "",
                "airportCode": "MWS",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Nanjing",
                "cityCode": "NKG",
                "airportCode": "NKG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Ruteng",
                "cityCode": "RTG",
                "airportCode": "RTG",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Maratua",
                "cityCode": "RTU",
                "airportCode": "RTU",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tomia Maranggo",
                "cityCode": "TQQ",
                "airportCode": "TQQ",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tana Toraja",
                "cityCode": "TRT",
                "airportCode": "TRT",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Tanjung Api",
                "cityCode": "VPM",
                "airportCode": "VPM",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "Indonesia",
                "country_kr": "인도네시아",
                "countryCode": "ID",
                "cityName": "Weda Bay",
                "cityCode": "WDB",
                "airportCode": "WDB",
                "gmt": "+7:00",
                "currency": "IDR"
            },
            {
                "country": "China",
                "countryCode": "CN",
                "cityName": "Beijing Daxing",
                "cityCode": "PKX",
                "airportName": "Beijing Daxing Int Airport",
                "airportCode": "PKX",
                "gmt": "GMT+8",
                "currency": "CNY"
            },
            {
                "country": "China",
                "countryCode": "CN",
                "cityName": "Xiamen",
                "cityName_kr": "Xiamen Gaoqi Int Airport",
                "cityCode": "XMN",
                "airportCode": "XMN",
                "gmt": "GMT+8",
                "currency": "CNY"
            }
        ]
    }
    AES_KEY = "qqZzhI2FOgPcaSQ=".encode()
    AES_IV = "qqZzhI2FOgPcaSQ=".encode()
    PAY_RSA_KEY = """-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/1ljsxI+r6qQraTFrHfWNrV41
vxumBF+4ILAG3WsN6HEBQU2wSUv/IyQmZkiys1ilOb+OOuQTH8OXMnqQg9E4epye
PW3L7IeOieSbIIDeSX6UpTWmT/Fs7moWZkN8RpuCV0u87n3AY2tQbtcSqwEKi2sx
zWLFwscoGn6N5yVIpQIDAQAB
-----END PUBLIC KEY-----"""
    PATTERNS_CHECK = [r'CHECKIN BAGGAGE ALLOWANCE (\d*)\s*KGS', '(\d*)\s*KG CHECKED BAGGAGE ALLOWED',
                      r'CHECKED BAGGAGE ALLOWANCE\s*(\d+)\s*kg']
    PATTERNS_HAND = [r'(\d)\s*\b(?:PIECE(?:S)? CABIN BAGGAGE(?: OF| TOTAL)? )(\d+)\s*KGS', '(\d*)KG CABIN BAGGAGE',
                     r'CABIN BAGGAGE OF\s*(\d+)\s*kg', r'(?:MAX\s*)?(\d+)\s*PIECES?\s*CABIN\s*BAGGAGE(?:\s*TOTAL)?\s*(\d+)\s*KGS?']

    PASSENGER_TITLE = {
        'ADT_M': 'MR',
        'ADT_F': 'MRS',
        'CHD_M': 'MSTR',
        'CHD_F': 'MISS'
    }
    AIRPORT_NAMES = {
        "Kota Kinabalu Airport": "BKI",
        "Tawau Airport": "TWU",
        "Kuala Lumpur International Airport": "KUL",
        "Chengdu Airport": "TFU",
        "Penang International Airport": "PEN",
        "Ngurah Rai Airport": "DPS",
        "Incheion International Airport": "ICN",
        "Hanoi Noibai International": "HAN",
        "Don Muang Airport": "DMK",
        "Hong Kong International": "HKG",
        "Male International Airport": "MLE",
        "Changi International Airport": "SIN",
        "Baiyun International": "CAN",
        "Hainan Meilan International": "HAK",
        "Jakarta Soekarno Hatta Intl Airport": "CGK",
        "Sultan Abdul Aziz Shah Airport": "SZB",
        "Da Nang Airport": "DAD",
        "Kunming Airport": "KMG",
        "Changsha Airport": "CSX",
        "Alor Star Airport": "AOR",
        "Medan Kuala Namu": "KNO",
        "Hat Yai Airport": "HDY",
        "Sultan Ismail International Airport": "JHB",
        "Phuket Airport": "HKT",
        "Langkawi Airport": "LGK",
        "Narita Airport": "NRT",
        "Hazrat Shahjalal Internatinal Airport": "DAC",
        "Chiang Kai Shek International Airport": "TPE",
        "Naha Field": "OKA",
        "Brisbane International Airport": "BNE",
        "Zhengzhou Airport": "CGO",
        "Palembang Airport": "PLM",
        "Melbourne International Airport": "MEL",
        "Batam Hang Nadim Airport": "BTH",
        "Lombok International Airport": "LOP",
        "Bintulu Airport": "BTU",
        "Kuching Airport": "KCH",
        "Krabi Airport": "KBV",
        "Quaid-e-Azam International Airport": "KHI",
        "Lahore Airport": "LHE",
        "Kota Bharu Airport": "KBR",
        "Xiamen - Gaoqi International": "XMN",
        "Perth Airport": "PER",
        "Indira Gandhi International Airport": "DEL",
        "Kathmandu Airport": "KTM",
        "Juanda Airport": "SUB",
        "Miri Airport": "MYY",
        "Kingsford Smith Airport": "SYD",
        "Dubai Airport": "DXB",
        "Tashkent Intl airport": "TAS",
        "Comoro Airport": "DIL",
        "Sandakan Airport": "SDK",
        "Sibu Airport": "SBW",
        "Sultan Syarif Kasim": "PKU",
        "Tiruchirapally Civil Airport": "TRZ",
        "Chhaprati Shivaji International Airport": "BOM",
        "Bengaluru": "BLR",
        "Kochi International Airport": "COK"
    }
