class Config:
    USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
    PRODUCT_CLASS_MAPPING = {
        'B': 'BASIC',
        'V': 'STANDARD',
        'Y': 'FLEX',
        'N': 'BIZ LITE',
    }
    BASE_CHECKED_BAGGAGE_MAPPING = {
        'B': 0,
        'V': 15,
        'N': 30,
    }
    BASE_HAND_BAGGAGE_WEIGHT = 10
    HAND_BAGGAGE_KEYWORDS = (
        'carry-on',
        'carry on',
        'cabin baggage',
        'hand baggage',
        'hand luggage',
        '随身行李',
        '手提行李',
        '기내수하물',
        '휴대수하물',
    )
    CHECKED_BAGGAGE_KEYWORDS = (
        'checked baggage',
        'checked-in baggage',
        'check-in baggage',
        'free baggage',
        'checkin baggage',
        '托运行李',
        '託運行李',
        '무료 수하물',
        '위탁 수하물',
        '위탁수하물',
    )
    DEPARTURE_STATIONS = [
        {
            "area": "韩国",
            "stationCode": "SEL",
            "cultureCode": "zh-CN",
            "cityCode": "SEL",
            "latitude": "372530N",
            "label": "首尔（所有机场）SEL",
            "mac": "Y",
            "differenceTime": "+09:00",
            "areaCode": "RGTP000001",
            "countryCode": "KR",
            "stationName": "首尔（所有机场）",
            "macCode": "SEL",
            "currencyCode": "KRW",
            "longitude": "1262230E",
            "macName": "首尔（所有机场）"
        },
        {
            "stationCode": "ICN",
            "cultureCode": "zh-CN",
            "stationName": "首尔(仁川)",
            "countryCode": "KR",
            "cityCode": "SEL",
            "currencyCode": "KRW",
            "latitude": "372530N",
            "longitude": "1262230E",
            "differenceTime": "+09:00",
            "macCode": "SEL",
            "macName": "首尔（所有机场）",
            "area": "韩国",
            "areaCode": "RGTP000001",
            "label": "首尔(仁川)ICN"
        },
        {
            "stationCode": "GMP",
            "cultureCode": "zh-CN",
            "stationName": "首尔(金浦)",
            "countryCode": "KR",
            "cityCode": "SEL",
            "currencyCode": "KRW",
            "latitude": "373304N",
            "longitude": "1264707E",
            "differenceTime": "+09:00",
            "macCode": "SEL",
            "macName": "首尔（所有机场）",
            "area": "韩国",
            "areaCode": "RGTP000001",
            "label": "首尔(金浦)GMP"
        },
        {
            "stationCode": "PUS",
            "cultureCode": "zh-CN",
            "stationName": "釜山",
            "countryCode": "KR",
            "cityCode": "PUS",
            "currencyCode": "KRW",
            "latitude": "351015N",
            "longitude": "1290750E",
            "differenceTime": "+09:00",
            "area": "韩国",
            "areaCode": "RGTP000001",
            "label": "釜山PUS"
        },
        {
            "stationCode": "CJU",
            "cultureCode": "zh-CN",
            "stationName": "济州",
            "countryCode": "KR",
            "cityCode": "CJU",
            "currencyCode": "KRW",
            "latitude": "333020N",
            "longitude": "1262942E",
            "differenceTime": "+09:00",
            "area": "韩国",
            "areaCode": "RGTP000001",
            "label": "济州CJU"
        },
        {
            "stationCode": "KWJ",
            "cultureCode": "zh-CN",
            "stationName": "光州",
            "countryCode": "KR",
            "cityCode": "KWJ",
            "currencyCode": "KRW",
            "latitude": "350724N",
            "longitude": "1264839E",
            "differenceTime": "+09:00",
            "area": "韩国",
            "areaCode": "RGTP000001",
            "label": "光州KWJ"
        },
        {
            "stationCode": "CJJ",
            "cultureCode": "zh-CN",
            "stationName": "清州",
            "countryCode": "KR",
            "cityCode": "CJJ",
            "currencyCode": "KRW",
            "latitude": "364300N",
            "longitude": "1273024E",
            "differenceTime": "+09:00",
            "area": "韩国",
            "areaCode": "RGTP000001",
            "label": "清州CJJ"
        },
        {
            "stationCode": "TAE",
            "cultureCode": "zh-CN",
            "stationName": "大邱",
            "countryCode": "KR",
            "cityCode": "TAE",
            "currencyCode": "KRW",
            "latitude": "355300N",
            "longitude": "1284000E",
            "differenceTime": "+09:00",
            "area": "韩国",
            "areaCode": "RGTP000001",
            "label": "大邱TAE"
        },
        {
            "stationCode": "HKD",
            "cultureCode": "zh-CN",
            "stationName": "函馆",
            "countryCode": "JP",
            "cityCode": "HKD",
            "currencyCode": "JPY",
            "latitude": "414612N",
            "longitude": "1404919E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "函馆HKD"
        },
        {
            "stationCode": "NRT",
            "cultureCode": "zh-CN",
            "stationName": "东京(成田)",
            "countryCode": "JP",
            "cityCode": "TYO",
            "currencyCode": "JPY",
            "latitude": "354550N",
            "longitude": "1402328E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "东京(成田)NRT"
        },
        {
            "stationCode": "KIX",
            "cultureCode": "zh-CN",
            "stationName": "大阪(关西)",
            "countryCode": "JP",
            "cityCode": "OSA",
            "currencyCode": "JPY",
            "latitude": "342526N",
            "longitude": "1351449E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "大阪(关西)KIX"
        },
        {
            "stationCode": "FUK",
            "cultureCode": "zh-CN",
            "stationName": "福冈",
            "countryCode": "JP",
            "cityCode": "FUK",
            "currencyCode": "JPY",
            "latitude": "333456N",
            "longitude": "1302712E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "福冈FUK"
        },
        {
            "stationCode": "NGO",
            "cultureCode": "zh-CN",
            "stationName": "名古屋",
            "countryCode": "JP",
            "cityCode": "NGO",
            "currencyCode": "JPY",
            "latitude": "345119N",
            "longitude": "1364830E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "名古屋NGO"
        },
        {
            "stationCode": "CTS",
            "cultureCode": "zh-CN",
            "stationName": "札幌",
            "countryCode": "JP",
            "cityCode": "SPK",
            "currencyCode": "JPY",
            "latitude": "424745N",
            "longitude": "1414009E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "札幌CTS"
        },
        {
            "stationCode": "OKA",
            "cultureCode": "zh-CN",
            "stationName": "冲绳",
            "countryCode": "JP",
            "cityCode": "OKA",
            "currencyCode": "JPY",
            "latitude": "261200N",
            "longitude": "1273900E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "冲绳OKA"
        },
        {
            "stationCode": "MYJ",
            "cultureCode": "zh-CN",
            "stationName": "松山",
            "countryCode": "JP",
            "cityCode": "MYJ",
            "currencyCode": "JPY",
            "latitude": "334920N",
            "longitude": "1324215E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "松山MYJ"
        },
        {
            "stationCode": "FSZ",
            "cultureCode": "zh-CN",
            "stationName": "静冈",
            "countryCode": "JP",
            "cityCode": "FSZ",
            "currencyCode": "JPY",
            "latitude": "344000N",
            "longitude": "1381000E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "静冈FSZ"
        },
        {
            "stationCode": "OIT",
            "cultureCode": "zh-CN",
            "stationName": "大分",
            "countryCode": "JP",
            "cityCode": "OIT",
            "currencyCode": "JPY",
            "latitude": "332846N",
            "longitude": "1314414E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "大分OIT"
        },
        {
            "stationCode": "HIJ",
            "cultureCode": "zh-CN",
            "stationName": "广岛",
            "countryCode": "JP",
            "cityCode": "HIJ",
            "currencyCode": "JPY",
            "latitude": "342610N",
            "longitude": "1325510E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "广岛HIJ"
        },
        {
            "stationCode": "KOJ",
            "cultureCode": "zh-CN",
            "stationName": "鹿儿岛",
            "countryCode": "JP",
            "cityCode": "KOJ",
            "currencyCode": "JPY",
            "latitude": "314812N",
            "longitude": "1304310E",
            "differenceTime": "+09:00",
            "area": "日本",
            "areaCode": "RGTP000006",
            "label": "鹿儿岛KOJ"
        },
        {
            "stationCode": "PVG",
            "cultureCode": "zh-CN",
            "stationName": "上海(浦东)",
            "countryCode": "CN",
            "cityCode": "SHA",
            "currencyCode": "CNY",
            "latitude": "310836N",
            "longitude": "1214819E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "上海(浦东)PVG"
        },
        {
            "stationCode": "HKG",
            "cultureCode": "zh-CN",
            "stationName": "香港",
            "countryCode": "HK",
            "cityCode": "HKG",
            "currencyCode": "HKD",
            "latitude": "221832N",
            "longitude": "1135452E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "香港HKG"
        },
        {
            "stationCode": "MFM",
            "cultureCode": "zh-CN",
            "stationName": "澳门",
            "countryCode": "MO",
            "cityCode": "MFM",
            "currencyCode": "MOP",
            "latitude": "220858N",
            "longitude": "1133529E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "澳门MFM"
        },
        {
            "stationCode": "KHH",
            "cultureCode": "zh-CN",
            "stationName": "高雄",
            "countryCode": "TW",
            "cityCode": "KHH",
            "currencyCode": "TWD",
            "latitude": "223421N",
            "longitude": "1202043E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "高雄KHH"
        },
        {
            "stationCode": "TPE",
            "cultureCode": "zh-CN",
            "stationName": "台北(桃园)",
            "countryCode": "TW",
            "cityCode": "TPE",
            "currencyCode": "TWD",
            "latitude": "250416N",
            "longitude": "1213237E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "台北(桃园)TPE"
        },
        {
            "stationCode": "PEK",
            "cultureCode": "zh-CN",
            "stationName": "北京(首都)",
            "countryCode": "CN",
            "cityCode": "BJS",
            "currencyCode": "CNY",
            "latitude": "400400N",
            "longitude": "1163600E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "北京(首都)PEK"
        },
        {
            "stationCode": "PKX",
            "cultureCode": "zh-CN",
            "stationName": "北京(大兴)",
            "countryCode": "CN",
            "cityCode": "BJS",
            "currencyCode": "CNY",
            "latitude": "393033N",
            "longitude": "1162438E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "北京(大兴)PKX"
        },
        {
            "stationCode": "TAO",
            "cultureCode": "zh-CN",
            "stationName": "青岛",
            "countryCode": "CN",
            "cityCode": "TAO",
            "currencyCode": "CNY",
            "latitude": "360600N",
            "longitude": "1201900E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "青岛TAO"
        },
        {
            "stationCode": "WEH",
            "cultureCode": "zh-CN",
            "stationName": "威海",
            "countryCode": "CN",
            "cityCode": "WEH",
            "currencyCode": "CNY",
            "latitude": "373000N",
            "longitude": "1220500E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "威海WEH"
        },
        {
            "stationCode": "HRB",
            "cultureCode": "zh-CN",
            "stationName": "哈尔滨",
            "countryCode": "CN",
            "cityCode": "HRB",
            "currencyCode": "CNY",
            "latitude": "454500N",
            "longitude": "1264000E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "哈尔滨HRB"
        },
        {
            "stationCode": "YNJ",
            "cultureCode": "zh-CN",
            "stationName": "延吉",
            "countryCode": "CN",
            "cityCode": "YNJ",
            "currencyCode": "CNY",
            "latitude": "423900N",
            "longitude": "1293000E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "延吉YNJ"
        },
        {
            "stationCode": "JMU",
            "cultureCode": "zh-CN",
            "stationName": "佳木斯",
            "countryCode": "CN",
            "cityCode": "JMU",
            "currencyCode": "CNY",
            "latitude": "465000N",
            "longitude": "1302100E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "佳木斯JMU"
        },
        {
            "stationCode": "SJW",
            "cultureCode": "zh-CN",
            "stationName": "石家庄",
            "countryCode": "CN",
            "cityCode": "SJW",
            "currencyCode": "CNY",
            "latitude": "380300N",
            "longitude": "1142800E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "石家庄SJW"
        },
        {
            "stationCode": "DYG",
            "cultureCode": "zh-CN",
            "stationName": "张家界",
            "countryCode": "CN",
            "cityCode": "DYG",
            "currencyCode": "CNY",
            "latitude": "290800N",
            "longitude": "1102900E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "张家界DYG"
        },
        {
            "stationCode": "KWL",
            "cultureCode": "zh-CN",
            "stationName": "桂林",
            "countryCode": "CN",
            "cityCode": "KWL",
            "currencyCode": "CNY",
            "latitude": "250800N",
            "longitude": "1101900E",
            "differenceTime": "+08:00",
            "area": "东北亚",
            "areaCode": "RGTP000002",
            "label": "桂林KWL"
        },
        {
            "stationCode": "PQC",
            "cultureCode": "zh-CN",
            "stationName": "富国",
            "countryCode": "VN",
            "cityCode": "PQC",
            "currencyCode": "USD",
            "latitude": "101018N",
            "longitude": "1035928E",
            "differenceTime": "+07:00",
            "area": "越南",
            "areaCode": "RGTP000007",
            "label": "富国PQC"
        },
        {
            "stationCode": "HAN",
            "cultureCode": "zh-CN",
            "stationName": "河内",
            "countryCode": "VN",
            "cityCode": "HAN",
            "currencyCode": "USD",
            "latitude": "210209N",
            "longitude": "1055324E",
            "differenceTime": "+07:00",
            "area": "越南",
            "areaCode": "RGTP000007",
            "label": "河内HAN"
        },
        {
            "stationCode": "DAD",
            "cultureCode": "zh-CN",
            "stationName": "岘港",
            "countryCode": "VN",
            "cityCode": "DAD",
            "currencyCode": "USD",
            "latitude": "160232N",
            "longitude": "1081213E",
            "differenceTime": "+07:00",
            "area": "越南",
            "areaCode": "RGTP000007",
            "label": "岘港DAD"
        },
        {
            "stationCode": "CXR",
            "cultureCode": "zh-CN",
            "stationName": "芽庄",
            "countryCode": "VN",
            "cityCode": "NHA",
            "currencyCode": "USD",
            "latitude": "115937N",
            "longitude": "1091330E",
            "differenceTime": "+07:00",
            "area": "越南",
            "areaCode": "RGTP000007",
            "label": "芽庄CXR"
        },
        {
            "stationCode": "MNL",
            "cultureCode": "zh-CN",
            "stationName": "马尼拉",
            "countryCode": "PH",
            "cityCode": "MNL",
            "currencyCode": "USD",
            "latitude": "143036N",
            "longitude": "1210106E",
            "differenceTime": "+08:00",
            "area": "菲律宾",
            "areaCode": "RGTP000008",
            "label": "马尼拉MNL"
        },
        {
            "stationCode": "CEB",
            "cultureCode": "zh-CN",
            "stationName": "宿务",
            "countryCode": "PH",
            "cityCode": "CEB",
            "currencyCode": "USD",
            "latitude": "101954N",
            "longitude": "1235424E",
            "differenceTime": "+08:00",
            "area": "菲律宾",
            "areaCode": "RGTP000008",
            "label": "宿务CEB"
        },
        {
            "stationCode": "TAG",
            "cultureCode": "zh-CN",
            "stationName": "邦劳薄荷岛",
            "countryCode": "PH",
            "cityCode": "TAG",
            "currencyCode": "USD",
            "latitude": "093951N",
            "longitude": "1235115E",
            "differenceTime": "+08:00",
            "area": "菲律宾",
            "areaCode": "RGTP000008",
            "label": "邦劳薄荷岛TAG"
        },
        {
            "stationCode": "CRK",
            "cultureCode": "zh-CN",
            "stationName": "克拉克",
            "countryCode": "PH",
            "cityCode": "CRK",
            "currencyCode": "USD",
            "latitude": "151100N",
            "longitude": "1203300E",
            "differenceTime": "+08:00",
            "area": "菲律宾",
            "areaCode": "RGTP000008",
            "label": "克拉克CRK"
        },
        {
            "stationCode": "BTH",
            "cultureCode": "zh-CN",
            "stationName": "巴淡岛",
            "countryCode": "ID",
            "cityCode": "BTH",
            "currencyCode": "IDR",
            "latitude": "010716N",
            "longitude": "1040708E",
            "differenceTime": "+07:00",
            "area": "印度尼西亚",
            "areaCode": "RGTP000011",
            "label": "巴淡岛BTH"
        },
        {
            "stationCode": "DPS",
            "cultureCode": "zh-CN",
            "stationName": "丹帕沙 (巴厘)",
            "countryCode": "ID",
            "cityCode": "DPS",
            "currencyCode": "IDR",
            "latitude": "084453S",
            "longitude": "1151003E",
            "differenceTime": "+08:00",
            "area": "印度尼西亚",
            "areaCode": "RGTP000011",
            "label": "丹帕沙 (巴厘)DPS"
        },
        {
            "stationCode": "SIN",
            "cultureCode": "zh-CN",
            "stationName": "新加坡",
            "countryCode": "SG",
            "cityCode": "SIN",
            "currencyCode": "SGD",
            "latitude": "012129N",
            "longitude": "1035438E",
            "differenceTime": "+08:00",
            "area": "新加坡",
            "areaCode": "RGTP000010",
            "label": "新加坡SIN"
        },
        {
            "stationCode": "BKK",
            "cultureCode": "zh-CN",
            "stationName": "曼谷",
            "countryCode": "TH",
            "cityCode": "BKK",
            "currencyCode": "THB",
            "latitude": "134109N",
            "longitude": "1004456E",
            "differenceTime": "+07:00",
            "area": "泰国/老挝",
            "areaCode": "RGTP000009",
            "label": "曼谷BKK"
        },
        {
            "stationCode": "CNX",
            "cultureCode": "zh-CN",
            "stationName": "清迈",
            "countryCode": "TH",
            "cityCode": "CNX",
            "currencyCode": "THB",
            "latitude": "184619N",
            "longitude": "0985806E",
            "differenceTime": "+07:00",
            "area": "泰国/老挝",
            "areaCode": "RGTP000009",
            "label": "清迈CNX"
        },
        {
            "stationCode": "VTE",
            "cultureCode": "zh-CN",
            "stationName": "万象",
            "countryCode": "LA",
            "cityCode": "VTE",
            "currencyCode": "USD",
            "latitude": "175905N",
            "longitude": "1023400E",
            "differenceTime": "+07:00",
            "area": "泰国/老挝",
            "areaCode": "RGTP000009",
            "label": "万象VTE"
        },
        {
            "stationCode": "BKI",
            "cultureCode": "zh-CN",
            "stationName": "哥打京那巴鲁",
            "countryCode": "MY",
            "cityCode": "BKI",
            "currencyCode": "MYR",
            "latitude": "055627N",
            "longitude": "1160300E",
            "differenceTime": "+08:00",
            "area": "菲律宾",
            "areaCode": "RGTP000012",
            "label": "哥打京那巴鲁BKI"
        },
        {
            "stationCode": "SPN",
            "cultureCode": "zh-CN",
            "stationName": "塞班",
            "countryCode": "MP",
            "cityCode": "SPN",
            "currencyCode": "USD",
            "latitude": "150722N",
            "longitude": "1454242E",
            "differenceTime": "+10:00",
            "area": "塞班",
            "areaCode": "RGTP000004",
            "label": "塞班SPN"
        },
        {
            "stationCode": "UBN",
            "cultureCode": "zh-CN",
            "stationName": "乌兰巴托",
            "countryCode": "MN",
            "cityCode": "ULN",
            "currencyCode": "USD",
            "latitude": "473836N",
            "longitude": "1064908E",
            "differenceTime": "+08:00",
            "area": "蒙古",
            "areaCode": "RGTP000005",
            "label": "乌兰巴托UBN"
        }
    ]
